"""tools/rebase_inventory.py's table of generated files is read from the tree (code review T6: its
curated table once named some 30 files, 27 of them gone): every generated source names its
generator, and only files that exist are listed."""
import os

import rebase_inventory


def test_every_generated_file_names_its_generator(repo):
    files = rebase_inventory.gen_files_in_tree()
    assert files and all(os.path.exists(repo / g) for g in files)
    table = rebase_inventory.gen_table()
    assert sorted(table) == files, "no 'Generated by tools/X.py' header: %s" % sorted(set(files) - set(table))
    for g, (tool, how, _) in table.items():
        assert os.path.exists(repo / tool), (g, tool)
        assert how.startswith(tool)


def test_a_file_without_a_header_has_no_entry(tmp_path):
    hand = tmp_path / "hand.inc"
    hand.write_text("// written by hand\n")
    gen = tmp_path / "gen.inc"
    gen.write_text("// Generated by tools/gen_addresses.py from x; do not edit.\n")
    table = rebase_inventory.gen_table([str(hand), str(gen)])
    assert list(table) == [str(gen)]
    assert "tools/check_generated.py checks it" in table[str(gen)][1]
