"""FunctionID tables of MultiplayRPC::LobbyProtocol and MO::BattleProtocol (3.7.0).
Names/FIDs from <Proto>::GetFunctionName decompiles; per-message fixed body size and FID store from
the Set<Name> serializers (constant stored to ProtocoledData+0x30, size to +0x24); signatures from
the dynamic symbol table.

Usage (from the repo root, after the decompiles below exist):
  tools/decomp.sh multiplayer-study-proto 'LobbyProtocol::GetFunctionName' 'BattleProtocol::GetFunctionName'
  tools/decomp.sh multiplayer-study-lobbyser 'MultiplayRPC::LobbyProtocoledData::(Set|Get)'
  tools/decomp.sh multiplayer-study-battleser 'MO::BattleProtocoledData::(Set|Get)'
  python3 docs/multiplayer/wire/gen_wire_tables.py [--inc OUT.inc] [DECOMP_DIR] [LIB] > wire-tables.md
  (--inc also writes a C++ table {protocol, name, fid, set_addr, size} like server/net/gen's)
"""
import os, re, subprocess, sys
REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../..'))
INC = None
if len(sys.argv) > 2 and sys.argv[1] == '--inc':
    INC = sys.argv[2]; del sys.argv[1:3]
D = (sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO, 'work/decomp')) + '/'
LIB = sys.argv[2] if len(sys.argv) > 2 else os.path.join(REPO, 'work/libSOA-3.7.0.so')
def names(path, proto):
    src = open(path).read()
    out = {}
    for blk in re.split(r'// ==== ', src)[1:]:
        if proto + '::GetFunctionName' not in blk.split('\n')[0]: continue
        for m in re.finditer(r'param_1 == (-?0x[0-9a-f]+)\) \{\s*return &\w+/\*"(\w+)"', blk):
            out[m.group(2)[1:]] = int(m.group(1), 16) & 0xffffffff
    return out
def setters(path, cls):
    src = open(path).read(); out = {}
    for blk in re.split(r'// ==== ', src)[1:]:
        head = blk.split('\n')[0]
        m = re.search(cls + r'::Set(\w+)\(', head)
        if not m: continue
        addr = re.search(r'@ ([0-9a-f]+)', blk).group(1)
        fid = re.search(r'\(param_\d \+ 0x30\) = (-?0x[0-9a-f]+);', blk)
        size = re.findall(r'\(param_\d \+ 0x24\) = (0x[0-9a-f]+|\w+);', blk)
        out[m.group(1)] = (addr, int(fid.group(1), 16) & 0xffffffff if fid else None, size[-1] if size else '?')
    return out
syms = subprocess.run(['nm', '-DC', LIB], capture_output=True, text=True).stdout
def sig(cls, name):
    m = re.search(r'([0-9a-f]+) T Aska::Yayoi::' + re.escape(cls) + '::Set' + name + r'\((.*)\)\n', syms)
    if not m: return None, ''
    a = m.group(2).replace('Aska::Yayoi::', '').replace('MultiplayRPC::', '').replace('Aska::', '').replace('Cryption::TChaCha20<false>*', 'ChaCha20*')
    return int(m.group(1), 16) + 0x100000, a
ROWS = []
for proto, cls, nf, sf in [('LobbyProtocol', 'MultiplayRPC::LobbyProtocoledData', 'multiplayer-study-proto', 'multiplayer-study-lobbyser'),
                           ('BattleProtocol', 'MO::BattleProtocoledData', 'multiplayer-study-proto', 'multiplayer-study-battleser')]:
    n = names(D + nf + '.resolved.c', proto); s = setters(D + sf + '.resolved.c', cls.split('::')[-1])
    print(f'\n### {proto}: {len(n)} FunctionIDs\n\n| Message | FunctionID | Set serializer (Ghidra) | body size (Set: +0x24) | parameters |\n|---|---|---|---|---|')
    for nm_, fid in sorted(n.items(), key=lambda kv: kv[0]):
        a, ps = sig(cls, nm_)
        st = s.get(nm_)
        chk = '' if not st or st[1] in (None, fid) else ' MISMATCH'
        ROWS.append((proto, nm_, fid, a or 0, st[2] if st else '0'))
        print(f"| {nm_} | `{fid:08x}`{chk} | {'@%08x' % a if a else '-'} | {st[2] if st else '-'} | {ps} |")
if INC:
    with open(INC, 'w') as o:
        o.write('// Generated by docs/multiplayer/wire/gen_wire_tables.py from the 3.7.0 decompiles: do not edit.\n'
                '// {protocol, message, FunctionID, Ghidra address of Set<message> (0 = none), fixed packet size (0 = variable/none)}\n')
        for proto, nm_, fid, a, size in ROWS:
            sz = size if re.fullmatch(r'0x[0-9a-f]+', str(size)) else '0'
            o.write(f'{{"{proto}", "{nm_}", 0x{fid:08x}u, 0x{a:08x}u, {sz}u}},\n')
