#!/usr/bin/env python3
"""The English text table: build, report and edit (docs/english.md 7.6, PLAN-english.md E1/M1/E3).

Files (data/english/, committed):
  master.tsv          the rows a person or an engine wrote: message_id, ja_sha1, en, source
                      (machine | agent | human | reviewed; agent: an AI agent wrote it, ranked as machine), engine, date, editor, note. Official, memory and
                      template English is NOT stored: the build derives it from the two master DBs.
  glossary.tsv        ja, en, kind, variants, source (human | machine), note. Global's terms
                      (official, Q8) are derived at load time (english_core.build_glossary), not stored.
  client-strings.tsv  message_id, en, note: the client's new strings (port_en_*), merged as human
                      rows with an empty ja_sha1.
  master-en.tsv       GENERATED by `build`: message_id, ja_sha1, en, source; OUR rows only (machine,
                      human, reviewed, the client strings) that pass their checks, post-processed,
                      sorted. Official / memory / template English is derived at build time from
                      data/basmaster-gl.sqlite3 (here and in the server's -en builder) and never
                      committed (the user's decision of 2026-10-07; docs/english.md 7.9 is the spec).
  story/TS_xxxx.tsv   machine/human/reviewed rows of one Scenario file (columns as master.tsv; no
                      Japanese: ja_sha1 is the SHA-1 of the line's text_value with REAL newlines)
  labels.tsv          the layout labels to translate (english.md 7.14): ja (master encoding), en, source,
                      engine, date, editor, note, sorted by ja. Only the Japanese listed here is replaced
                      in the scenes' node trees (placeholders such as ああああ are left out). A row is
                      "derived" with no en (the server takes the English of the master row with the same
                      Japanese, or Global's memory, at build time; english_derive.h resolve_labels) or our
                      own English (machine | agent | human | reviewed), checked as a master row.
  story-en/TS_xxxx.tsv
                      GENERATED: our story rows per Scenario file, after the strict story checks
                      and the re-break to the 480 px message window. Needs the download's
                      Scenario/ (work/SOA-3.7.0-canonical-data.zip); without it `build` and `build --check` skip the story part.
  `derive --out DIR`  the FULL resolved tables (master-en-full.tsv, story-en-full/TS_*.tsv and
                      index.tsv with per-file completeness): the reference for the C++ port.
All TSVs: UTF-8, a header line, no quoting, a line break inside a text is the two characters \\n.

Precedence per message_id (english.md 7.6): human/reviewed > official (Global by id, the five
filters; plus Global token rows rewritten by E3) > memory (exact) / template > machine / agent > Japanese.
A candidate that fails a check (english.md 7.5) is not served; the next one is tried, and the failure
is listed by `report`. A table row whose ja_sha1 differs from the current Japanese is stale: not served.

Usage:
  tools/english_text.py build [--check]          write master-en.tsv, story-en/ and glossary.tsv (our
                                                 rows; --check: exit 1 when the committed files are stale)
  tools/english_text.py derive --out DIR         the full resolved tables (all sources)
  tools/english_text.py report [--out DIR]       coverage per source and prefix, failing rows, width
                                                 outliers, Q7 rows, token gaps, glossary conflicts,
                                                 rows over a fixed text box (BOXES: boxes.tsv)
                                                 (summary to stdout, lists to work/english/report/)
  tools/english_text.py show ID
  tools/english_text.py set ID TEXT --by NAME [--note N] [--force]
  tools/english_text.py review ID... --by NAME   machine -> reviewed (kept unchanged)
  tools/english_text.py stale                    table rows whose Japanese changed
  tools/english_text.py export-po [--out DIR]    one .po per prefix (work/english/po/)
  tools/english_text.py import-po FILE... --by NAME
  tools/english_text.py export-csv [--out FILE]  (work/english/english.csv)
  tools/english_text.py import-csv FILE --by NAME
  tools/english_text.py glossary-weak [--apply]  official ui/skill/talent/speaker terms Global's own
                                                 text doesn't follow (>= half of >= 3 rows): --apply
                                                 removes them with human rows; also lists machine names
                                                 Global's text contradicts
  tools/english_text.py labels [--check]        check labels.tsv (format, order, every row with English passes
                                                 the machine checks); exit 1 on a problem
  tools/english_text.py label-set JA TEXT --by NAME [--source agent|human] [--note N]
                                                 our English for a layout label (JA in the master encoding)
  tools/english_text.py import-mt CHECKPOINT.jsonl [--replace]
                                                 machine rows from the MT runner's checkpoint (master
                                                 rows, story rows: "kind": "story", or layout labels:
                                                 "kind": "label", into labels.tsv); rows failing
                                                 the checks go to work/english/mt-rejected.tsv
                                                 (mt-rejected-story.tsv)
Common options: --data DIR (data/english) --master DB --gl DB --scenario DIR --font FILE --no-build
"""
import argparse
import collections
import csv
import datetime
import json
import pathlib
import sys
import unicodedata

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))

import english_core as C  # noqa: E402

DATA = REPO / "data/english"
WORK = REPO / "work/english"
TABLE_COLS = ["message_id", "ja_sha1", "en", "source", "engine", "date", "editor", "note"]
GLOSSARY_COLS = ["ja", "en", "kind", "variants", "source", "note"]
CLIENT_COLS = ["message_id", "en", "note"]
OUT_COLS = ["message_id", "ja_sha1", "en", "source"]
REJECT_COLS = ["message_id", "ja_sha1", "engine", "date", "en", "problems"]
LABEL_COLS = ["ja", "en", "source", "engine", "date", "editor", "note"]
HUMAN = ("human", "reviewed")
# Rows an engine or an agent wrote, which a person has not checked: served only where no official,
# memory or template row passes (english.md 7.9 step 7). `agent` is a row an AI agent wrote by hand
# (`set --source agent`; its editor names the agent), ranked and checked like `machine`.
MACHINE = ("machine", "agent")
DERIVED = ("official", "memory", "template")
GLOSSARY_RANK = {"human": 0, "official": 1, "machine": 2}


# ---------------------------------------------------------------- TSV files

def _field(s):
    s = "" if s is None else str(s)
    if any(c in s for c in "\t\r\n"):
        raise ValueError(f"tab or line break in a field: {s!r}")
    return s


def tsv_text(cols, rows):
    out = ["\t".join(cols)]
    for r in rows:
        out.append("\t".join(_field(r.get(c, "")) for c in cols))
    return "\n".join(out) + "\n"


def read_tsv(path, cols, required=False):
    """[{col: value}] of a TSV with exactly this header; [] for a missing file unless required."""
    path = pathlib.Path(path)
    if not path.exists():
        if required:
            raise FileNotFoundError(path)
        return []
    lines = path.read_text(encoding="utf-8").split("\n")
    if lines and lines[-1] == "":
        lines.pop()
    if not lines or lines[0].split("\t") != cols:
        raise ValueError(f"{path}: header must be {cols}")
    rows = []
    for n, line in enumerate(lines[1:], 2):
        f = line.split("\t")
        if len(f) != len(cols):
            raise ValueError(f"{path}:{n}: {len(f)} fields, want {len(cols)}")
        rows.append(dict(zip(cols, f)))
    return rows


def write_if_changed(path, text):
    path = pathlib.Path(path)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


_SOURCES = {}  # read-only sources, shared by the commands of one process (the tests)


class Ctx:
    def __init__(self, data=DATA, master=C.MASTER_DB, gl=C.GLOBAL_DB, scenario=C.SCENARIO, font=None,
                 work=WORK):
        self.data = pathlib.Path(data)
        self.master, self.gl, self.scenario, self.font = master, gl, scenario, font
        self.work = pathlib.Path(work)
        self._src = self._font = None

    @property
    def src(self):
        if self._src is None:
            key = (str(self.master), str(self.gl), str(self.scenario))
            if key not in _SOURCES:
                _SOURCES[key] = C.Sources(master=self.master, gl=self.gl, scenario=self.scenario)
            self._src = _SOURCES[key]
        return self._src

    @property
    def fnt(self):
        if self._font is None:
            self._font = C.Font(self.font)
        return self._font

    def path(self, name):
        return self.data / name

    def table(self):
        rows = read_tsv(self.path("master.tsv"), TABLE_COLS)
        t = {}
        for r in rows:
            if r["message_id"] in t:
                raise ValueError(f"master.tsv: {r['message_id']} twice")
            if r["source"] not in MACHINE + HUMAN:
                raise ValueError(f"master.tsv: {r['message_id']}: source {r['source']!r} (machine|agent|human|reviewed)")
            t[r["message_id"]] = r
        return t

    def write_table(self, t):
        rows = [t[m] for m in sorted(t)]
        write_if_changed(self.path("master.tsv"), tsv_text(TABLE_COLS, rows))

    def story_tables(self):
        """{message_id: row} of data/english/story/TS_*.tsv; each row also carries its "file"."""
        t = {}
        for p in sorted(self.path("story").glob("TS_*.tsv")):
            for r in read_tsv(p, TABLE_COLS):
                if r["message_id"] in t:
                    raise ValueError(f"{p}: {r['message_id']} twice")
                if r["source"] not in MACHINE + HUMAN:
                    raise ValueError(f"{p}: {r['message_id']}: source {r['source']!r} (machine|agent|human|reviewed)")
                r["file"] = p.stem
                t[r["message_id"]] = r
        return t

    def write_story_tables(self, t):
        by = collections.defaultdict(list)
        for m in sorted(t):
            by[t[m]["file"]].append(t[m])
        for stem, rows in by.items():
            write_if_changed(self.path("story") / f"{stem}.tsv", tsv_text(TABLE_COLS, rows))
        for p in self.path("story").glob("TS_*.tsv"):
            if p.stem not in by:
                p.unlink()


# ---------------------------------------------------------------- glossary

def glossary_rows(ctx):
    """glossary.tsv's rows: Global's terms regenerated, the human and machine rows of the file kept."""
    src = ctx.src
    if not hasattr(src, "_english_glossary"):
        src._english_glossary = C.build_glossary(src)
    official = src._english_glossary
    rows = [{"ja": ja, "en": t["en"], "kind": t["kind"], "variants": " | ".join(t["variants"]),
             "source": "official", "note": ""} for ja, t in official.items()]
    for r in read_tsv(ctx.path("glossary.tsv"), GLOSSARY_COLS):
        if r["source"] == "official":
            continue
        if r["source"] not in GLOSSARY_RANK:
            raise ValueError(f"glossary.tsv: {r['ja']}: source {r['source']!r} (official|human|machine)")
        rows.append(r)
    rows.sort(key=lambda r: (r["ja"], GLOSSARY_RANK[r["source"]], r["en"]))
    return rows


WEAK_KINDS = ("ui", "skill", "talent", "speaker")  # not proper nouns of people, items, missions, areas
WEAK_MIN_ROWS, WEAK_MISS = 3, 0.5


def glossary_adherence(ctx, glossary):
    """{term: (rows, misses)}: how often Global's own official English (master rows by id and story
    lines) uses each glossary term's English where the Japanese has the term."""
    b = build(ctx)
    src = ctx.src
    n = collections.defaultdict(lambda: [0, 0])

    def acc(ja, en):
        miss = {t for t, _ in C.glossary_misses(ja, en, glossary)}
        for t in C.glossary_hits(ja, glossary):
            n[t][0] += 1
            n[t][1] += t in miss
    for mid, (h, e, source) in b.out.items():
        if source == "official" and mid in src.jp_rows:
            acc(C.unesc(src.jp_rows[mid]), C.unesc(e))
    s = build_story(ctx, b.glossary)
    if s is not None:
        for mid, (h, e, source) in s.out.items():
            if source == "official":
                acc(s.derived.lines[mid][1], C.unesc(e))
    return {t: tuple(v) for t, v in n.items()}


def cmd_glossary_weak(ctx, a):
    """The rule for demoting a Global glossary term (Q8 keeps Global's terms, but a term Global's own
    text doesn't follow only makes good MT rows fail): an official term of a kind in WEAK_KINDS whose
    English Global's official rows miss in at least half of at least 3 rows. Lists them (and the
    machine names Global's text contradicts); --apply adds a human row with an empty en for each
    weak term (a human row of the same term is left alone)."""
    rows = glossary_rows(ctx)
    official = glossary_dict([r for r in rows if r["source"] == "official"])
    machine = glossary_dict([r for r in rows if r["source"] == "machine"])
    adh = glossary_adherence(ctx, {**machine, **official})
    weak = [(t, official[t], adh[t]) for t in sorted(official)
            if official[t]["kind"] in WEAK_KINDS and t in adh and adh[t][0] >= WEAK_MIN_ROWS
            and adh[t][1] >= WEAK_MISS * adh[t][0]]
    contra = [(t, machine[t], adh[t]) for t in sorted(machine)
              if t not in official and t in adh and adh[t][0] >= WEAK_MIN_ROWS and adh[t][1] >= WEAK_MISS * adh[t][0]]
    humans = {r["ja"] for r in rows if r["source"] == "human"}
    print("weak official terms (Global's own rows miss them):")
    for t, g, (r, m) in weak:
        print(f"  {t}\t{g['en']}\t{g['kind']}\tmissed in {m} of {r}" + ("\t(has a human row)" if t in humans else ""))
    print("machine names Global's official text contradicts (give them Global's spelling as human rows):")
    for t, g, (r, m) in contra:
        print(f"  {t}\t{g['en']}\tmissed in {m} of {r}" + ("\t(has a human row)" if t in humans else ""))
    if a.apply:
        for t, g, (r, m) in weak:
            if t not in humans:
                rows.append({"ja": t, "en": "", "kind": g["kind"], "variants": "", "source": "human",
                             "note": f"demoted (glossary-weak): Global's official English misses '{g['en']}' in {m} of {r} rows"})
        rows.sort(key=lambda r: (r["ja"], GLOSSARY_RANK[r["source"]], r["en"]))
        write_if_changed(ctx.path("glossary.tsv"), tsv_text(GLOSSARY_COLS, rows))
        rebuild(ctx, a)
    return 0


def glossary_dict(rows):
    """{ja: {"en", "variants", "kind", "source"}}: per term the human row, else the official, else the
    machine one (M2's new names). A row with an empty en removes the term."""
    best = {}
    for r in rows:
        cur = best.get(r["ja"])
        if cur is None or GLOSSARY_RANK[r["source"]] < GLOSSARY_RANK[cur["source"]]:
            best[r["ja"]] = r
    return {ja: {"en": r["en"], "variants": [v for v in r["variants"].split(" | ") if v],
                 "kind": r["kind"], "source": r["source"]}
            for ja, r in sorted(best.items()) if r["en"]}


# ---------------------------------------------------------------- build

class Built:
    pass


def finish(ctx, glossary, source, en, ja):
    """(served English in the master encoding, problems) of one candidate for a JP row (`ja` in the
    master encoding; "" for a new message_id). Folding, %% in printf rows, and for derived rows a
    re-break when Global dropped the Japanese row's line breaks (english.md 3.2: the 459 rows);
    Global's own line breaks are kept."""
    font = ctx.fnt
    jn = C.unesc(ja)
    e = C.unesc(en)
    if source in HUMAN:
        e = unicodedata.normalize("NFC", e)
    e = font.fold(e)
    e = C.fix_percent(e, ja)
    rebroken = False
    if source in DERIVED and "\n" in jn and "\n" not in e:
        e = font.rebreak(e, max(font.widest(jn), 200))
        rebroken = True
    if not ja:  # a new message_id (client strings): no Japanese to compare tokens with
        probs = C.check(e, e, font)
    else:
        probs = C.check(jn, e, font, glossary if source not in DERIVED else None,
                        tags="strict" if source in MACHINE else "subset")
    return C.esc(e), probs, rebroken


class Derived:
    """The part of a build that depends only on the master DBs and the font: per JP row its class
    and its official / memory / template candidate, already finished and checked. Cached per Sources
    (they are read-only), so the edit commands and the tests rebuild quickly."""

    def __init__(self, ctx):
        src, font = ctx.src, ctx.fnt
        mem = C.Memory(src)
        self.rows = {}        # mid -> (ja, sha1, klass, [(source, en, probs, rebroken, (ja px, en px) or None)])
        self.e3, self.token_gaps, self.q7 = [], [], []
        self.official = {}    # mid -> Global's English as stored (for the human override list)
        # mid -> rule ("id-ws" | "memory-ws") of the white-space-insensitive matches (english.md
        # 7.9 id-ws, memory-ws): served as official / memory, listed by `report` (matched.tsv)
        self.matched = {}
        for mid in sorted(src.jp_rows):
            ja = src.jp_rows[mid] or ""
            jn = C.unesc(ja)
            cands = []
            off = src.official(mid, ja)
            rule = C.same_ja(src.gl_ja.get(mid), ja)
            klass = None
            if off is not None:
                klass = "official"
                cands.append(("official", off))
            else:
                e3, why = src.official_e3(mid, ja)
                if e3 is not None:
                    klass = "official_e3"
                    self.e3.append(mid)
                    cands.append(("official", e3))
                elif why:
                    self.token_gaps.append((mid, ja, src.gl_en[mid], why))
            if klass is not None and rule == "id-ws":
                self.matched[mid] = "id-ws"
            if klass is None:
                if not C.has_kana(ja):
                    klass = "neutral"
                else:
                    m, kind = mem.lookup(ja)
                    if m is not None:
                        klass = kind
                        cands.append(("template" if kind == "template" else "memory", m))
                        if kind == "exact_ws":
                            self.matched[mid] = "memory-ws"
                    else:
                        klass = "gap"
            if cands and cands[0][0] == "official":
                self.official[mid] = cands[0][1]
            if C.has_kana(ja) and src.gl_english(mid) and not rule:
                self.q7.append(mid)  # Global's English translates an older Japanese text (Q7)
            done = []
            for source, en in cands:
                e, probs, rebroken = finish(ctx, None, source, en, ja)
                done.append((source, e, probs, rebroken, widths(font, jn, C.unesc(e))))
            self.rows[mid] = (ja, C.sha1(ja), klass, done)

    @staticmethod
    def of(ctx):
        cache = ctx.src.__dict__.setdefault("_english_derived", {})
        key = str(ctx.font)
        if key not in cache:
            cache[key] = Derived(ctx)
        return cache[key]


def widths(font, jn, en):
    """(ja px, en px) of a single-line row, else None."""
    if "\n" in jn or "\n" in en:
        return None
    return font.widest(jn), font.widest(en)


def build(ctx):
    """Everything `build` and `report` need, computed in memory."""
    src, font = ctx.src, ctx.fnt
    d = Derived.of(ctx)
    g_rows = glossary_rows(ctx)
    glossary = glossary_dict(g_rows)
    table = ctx.table()
    client = read_tsv(ctx.path("client-strings.tsv"), CLIENT_COLS)
    b = Built()
    b.glossary_rows, b.glossary = g_rows, glossary
    b.table = table
    b.out = {}            # mid -> (ja_sha1, en, source)
    b.klass = {}          # mid -> official | official_e3 | exact | exact_ws | template | neutral | gap
    b.candidates = collections.Counter()
    b.served = collections.Counter()
    b.failures = []       # {message_id, source, en, problems}
    b.token_gaps = d.token_gaps  # (mid, ja, gl_en, reason)
    b.stale = []          # (mid, source, table sha1, current sha1)
    b.width = []          # (mid, source, ja px, en px): single-line rows over 1.5x the Japanese
    b.width_all = []      # the same for every single-line row
    b.overrides = []      # (mid, source, official en, served en)
    b.rebroken = collections.Counter()
    b.e3, b.q7, b.matched = d.e3, d.q7, d.matched
    b.ours = {}           # mid -> (ja_sha1, en, source): our rows (table + client strings) that pass
    for mid, (ja, h, klass, derived) in d.rows.items():
        cands = []
        t = table.get(mid)
        if t and t["ja_sha1"] != h:
            b.stale.append((mid, t["source"], t["ja_sha1"], h))
            t = None
        if t and t["source"] in HUMAN:
            cands.append((t["source"], t["en"]))
        cands += derived
        if t and t["source"] in MACHINE:
            cands.append((t["source"], t["en"]))
        b.klass[mid] = klass
        b.candidates[klass] += 1
        if t and t["source"] in MACHINE and mid not in b.ours:
            e, probs, _ = finish(ctx, glossary, t["source"], t["en"], ja)
            if not probs:
                b.ours[mid] = (h, e, t["source"])  # committed even where a derived row wins
        for c in cands:
            if len(c) == 2:  # a table row: finish it now (the glossary may have changed)
                source = c[0]
                e, probs, rebroken = finish(ctx, glossary, source, c[1], ja)
                w = widths(font, C.unesc(ja), C.unesc(e))
                if not probs:
                    b.ours[mid] = (h, e, source)
            else:
                source, e, probs, rebroken, w = c
            if probs:
                b.failures.append({"message_id": mid, "source": source, "en": e, "problems": probs})
                continue
            b.out[mid] = (h, e, source)
            b.served[source] += 1
            if rebroken:
                b.rebroken[source] += 1
            off = d.official.get(mid)
            if source in HUMAN and off is not None and C.esc(C.unesc(off)) != e:
                b.overrides.append((mid, source, off, e))
            if w:
                b.width_all.append((mid, source, w[0], w[1]))
                if w[1] > 1.5 * max(w[0], 100):
                    b.width.append((mid, source, w[0], w[1]))
            break
    # new message_ids: master.tsv human rows without a JP row, then the client's strings
    extra = {}
    for r in client:
        extra[r["message_id"]] = ("human", r["en"])
    for mid, t in sorted(table.items()):
        if mid in src.jp_rows:
            continue
        if t["ja_sha1"] or t["source"] not in HUMAN:
            b.stale.append((mid, t["source"], t["ja_sha1"], ""))
            continue
        extra[mid] = (t["source"], t["en"])
    for mid in sorted(extra):
        source, en = extra[mid]
        if mid in src.jp_rows:
            b.failures.append({"message_id": mid, "source": source, "en": en,
                               "problems": {"id": "a client string's id is a JP master message_id"}})
            continue
        e, probs, _ = finish(ctx, glossary, source, en, "")
        if probs:
            b.failures.append({"message_id": mid, "source": source, "en": e, "problems": probs})
            continue
        b.out[mid] = ("", e, source)
        b.ours[mid] = ("", e, source)
        b.served[source] += 1
        b.candidates["client"] += 1

    def text(rows):
        return tsv_text(OUT_COLS, [{"message_id": m, "ja_sha1": rows[m][0], "en": rows[m][1], "source": rows[m][2]}
                                   for m in sorted(rows, key=lambda m: m.encode())])
    b.master_en = text(b.ours)       # committed: our rows only (the user's decision of 2026-10-07)
    b.master_en_full = text(b.out)   # `derive`: the resolved table, the C++ port's reference
    # committed: our glossary rows only; Global's terms are derived (glossary_rows)
    b.glossary_text = tsv_text(GLOSSARY_COLS, [r for r in g_rows if r["source"] != "official"])
    return b


def write_build(ctx, b):
    ch = write_if_changed(ctx.path("master-en.tsv"), b.master_en)
    ch |= write_if_changed(ctx.path("glossary.tsv"), b.glossary_text)
    if not ctx.path("client-strings.tsv").exists():
        write_if_changed(ctx.path("client-strings.tsv"), tsv_text(CLIENT_COLS, []))
    return ch


def summary(b):
    return (f"{len(b.out)} rows English: " + ", ".join(f"{k} {v}" for k, v in sorted(b.served.items()))
            + f"; {len(b.failures)} failing candidates, {len(b.stale)} stale table rows")


# ---------------------------------------------------------------- story (phase 2: C3, E7, M4)
#
# data/english/story/TS_xxxx.tsv     the machine/human/reviewed rows of one Scenario file (TABLE_COLS;
#                                     no Japanese: the story's Japanese is not in git, english.md 7.6)
# data/english/story-en/TS_xxxx.tsv  GENERATED: message_id, ja_sha1, en, source of every line of the
#                                     file that has English (official, E3, table rows), after the
#                                     strict story checks and the re-break to the message window
# data/english/story-en/index.tsv    GENERATED: file, lines, need (lines with kana or kanji),
#                                     english (of those, lines with a row), complete (yes|no): the
#                                     server serves TS_x-en.msgp only when complete (Q12)
# A story line's ja_sha1 is the SHA-1 of the Scenario row's text_value exactly as the file holds it
# (UTF-8, REAL newlines), unlike the master's two-character \n. The Japanese comes from the 3.7.0
# download (Scenario/ in work/SOA-3.7.0-canonical-data.zip) at build time; without it the story part is skipped.

STORY_BUDGET = 480   # px per line of the message window (font px; measured on a --lang en campaign shot, english.md 7.5)
# (d) <player> expands to the player's name: counted as 120 px (about 8 Latin letters) when breaking
PLAYER_PX = {"<player>": 120}
STORY_SOURCES = ("official", "machine", "agent", "human", "reviewed")
STORY_LONG = 5       # lines: a served line needing this many or more is reported (E7)
# E13: the window holds STORY_LINES lines; n lines are 40 n - 10 high at its FontSize 30 (lines 40
# apart, 30 high: CEventScenarioMessageWindow::Show, CalcStringRect; (b) client evidence). A line
# over STORY_LINES lines gets the font scale k_n = (40 * 4 - 10) / (40 n - 10) from the client
# (platform370 text_370.cpp h_window_change), so it is broken at STORY_BUDGET / k_n, for the fewest
# n that holds it (english.md 7.13).
STORY_LINES = 4


def story_budget(n):
    """The break width for n window lines: STORY_BUDGET up to STORY_LINES lines, else STORY_BUDGET /
    k_n = STORY_BUDGET * (40 n - 10) // (40 * STORY_LINES - 10) (an integer: 128 n - 32)."""
    return STORY_BUDGET if n <= STORY_LINES else STORY_BUDGET * (40 * n - 10) // (40 * STORY_LINES - 10)


def story_break(font, e):
    """`e` broken for the message window (E7, E13): for the fewest n (1, 2, ...) whose break at
    story_budget(n) takes at most n lines (the greedy break never gains lines at a wider width, so
    that is the largest font the client can give it)."""
    for n in range(1, 25):
        r = font.rebreak(e, story_budget(n), PLAYER_PX)
        if r.count("\n") + 1 <= n:
            return r
    return r


def story_finish(ctx, glossary, source, en, ja):
    """(served English in the two-character \\n encoding, problems, number of lines) of a story
    candidate; `ja` with real newlines. Every line is re-broken at spaces to STORY_BUDGET (Global's
    breaks were made for a wider window, english.md 6.5)."""
    font = ctx.fnt
    e = C.unesc(en)
    if source in HUMAN or source in MACHINE:
        e = unicodedata.normalize("NFC", e)
    e = font.fold(e).strip()
    e = story_break(font, e)
    probs = C.check(ja, e, font, glossary if source not in DERIVED else None, tags="strict")
    tags = C.TAG.findall(e)
    bad = [t for t in tags if not C.STORY_TAG.fullmatch(t)]
    if source in MACHINE and C.runaway(ja, e):
        probs["runaway"] = len(e)  # an engine stuck repeating a sound ("CAPTAIIII...", "ka-ka-ka-...")
    if bad:
        probs["story_tag"] = bad  # an unknown tag likely crashes ParseMessage (english.md 3.3)
    elif source not in MACHINE and "tags" in probs:
        # Global's (and a person's) English may colour other words or name <player> where JP says
        # 艦長: harmless as long as every tag is one ParseMessage reads and <font> is balanced.
        # An engine must keep the Japanese line's tags exactly.
        opens = sum(1 for t in tags if t.startswith("<font"))
        if opens == tags.count("</font>"):
            del probs["tags"]
    return C.esc(e), probs, e.count("\n") + 1


class StoryDerived:
    """Per story line: file, Japanese, sha1, class and the official candidate (Global by id or E3),
    finished; cached per Sources like Derived. None without the Scenario files."""

    def __init__(self, ctx):
        src = ctx.src
        self.lines = {}       # mid -> (stem, ja, sha1, klass, [(source, en, probs, nlines)])
        self.files = collections.defaultdict(list)
        self.token_gaps = []
        for stem, mid, ja in src.story():
            cands, klass = [], None
            en = src.story_official(mid, ja)
            if en is not None:
                klass = "official"
            else:
                en, why = src.story_official_e3(mid, ja)
                if en is not None:
                    klass = "official_e3"
                elif why:
                    self.token_gaps.append((mid, C.esc(ja), src.gl_en.get(mid, ""), why))
            if en is not None:
                cands.append(("official",) + story_finish(ctx, None, "official", en, ja))
            if klass is None:
                klass = "gap" if C.has_kana(ja) else "neutral"
            elif not C.has_kana(ja):
                klass = "neutral"  # language-neutral (……, ！？): served if Global has English, never needed
            self.lines[mid] = (stem, ja, C.sha1(ja), klass, cands)
            self.files[stem].append(mid)

    @staticmethod
    def of(ctx):
        if not ctx.src.has_story():
            return None
        cache = ctx.src.__dict__.setdefault("_english_story", {})
        key = str(ctx.font)
        if key not in cache:
            cache[key] = StoryDerived(ctx)
        return cache[key]


def build_story(ctx, glossary, tables=None):
    """The story part of a build, or None without the Scenario files."""
    d = StoryDerived.of(ctx)
    if d is None:
        return None
    tables = ctx.story_tables() if tables is None else tables
    s = Built()
    s.derived = d
    s.out = {}            # mid -> (ja_sha1, en, source)
    s.ours = {}           # the same for our rows (story/TS_*.tsv) that pass
    s.failures, s.stale, s.long = [], [], []
    s.files = {}          # stem -> counts
    for mid, t in sorted(tables.items()):
        if mid not in d.lines:
            s.stale.append((mid, t["source"], t["ja_sha1"], ""))
    for stem in sorted(d.files):
        c = collections.Counter()
        for mid in d.files[stem]:
            _, ja, h, klass, derived = d.lines[mid]
            c["lines"] += 1
            if klass != "neutral":
                c["need"] += 1
            t = tables.get(mid)
            if t and t["ja_sha1"] != h:
                s.stale.append((mid, t["source"], t["ja_sha1"], h))
                t = None
            cands = []
            if t and t["source"] in HUMAN:
                cands.append((t["source"], t["en"]))
            cands += derived
            if t and t["source"] in MACHINE:
                cands.append((t["source"], t["en"]))
            if t:  # our row, committed whenever it passes (even where a derived line wins)
                e, probs, _ = story_finish(ctx, glossary, t["source"], t["en"], ja)
                if not probs:
                    s.ours[mid] = (h, e, t["source"])
            failed = False
            for cand in cands:
                if len(cand) == 2:
                    source = cand[0]
                    e, probs, nl = story_finish(ctx, glossary, source, cand[1], ja)
                else:
                    source, e, probs, nl = cand
                if probs:
                    s.failures.append({"message_id": mid, "file": stem, "source": source, "en": e, "problems": probs})
                    failed = True
                    continue
                s.out[mid] = (h, e, source)
                c[source] += 1
                if klass != "neutral":
                    c["english"] += 1
                if nl >= STORY_LONG:
                    s.long.append((mid, stem, source, nl, e))
                break
            else:
                if klass != "neutral":
                    c["failing" if failed else "missing"] += 1
        s.files[stem] = c
    def texts(rows_of):
        out = {}
        for stem in sorted(d.files):
            rows = [{"message_id": m, "ja_sha1": rows_of[m][0], "en": rows_of[m][1], "source": rows_of[m][2]}
                    for m in sorted(d.files[stem], key=lambda m: m.encode()) if m in rows_of]
            if rows:
                out[stem] = tsv_text(OUT_COLS, rows)
        return out
    s.texts = texts(s.ours)        # committed: data/english/story-en/TS_*.tsv, our rows only
    s.full_texts = texts(s.out)    # `derive`: story-en-full/TS_*.tsv
    s.index = tsv_text(["file", "lines", "need", "english", "complete"],
                       [{"file": stem, "lines": c["lines"], "need": c["need"], "english": c["english"],
                         "complete": "yes" if c["english"] == c["need"] else "no"}
                        for stem, c in sorted(s.files.items())])
    return s


def story_outputs(ctx, s):
    """{path: text} of the committed story files: our rows per Scenario file."""
    return {ctx.path("story-en") / f"{stem}.tsv": text for stem, text in s.texts.items()}


def write_story(ctx, s):
    outs = story_outputs(ctx, s)
    for p, text in outs.items():
        write_if_changed(p, text)
    for p in list(ctx.path("story-en").glob("TS_*.tsv")) + [ctx.path("story-en") / "index.tsv"]:
        if p.exists() and p not in outs:
            p.unlink()  # a file with none of our rows any more (index.tsv: now derive's)


def story_summary(s):
    if s is None:
        return "story: skipped (no Scenario files: work/SOA-3.7.0-canonical-data.zip)"
    tot = collections.Counter()
    for c in s.files.values():
        tot.update(c)
    complete = sum(1 for c in s.files.values() if c["english"] == c["need"])
    return (f"story: {tot['english']} of {tot['need']} lines English ("
            + ", ".join(f"{k} {tot[k]}" for k in C_SOURCES if tot[k])
            + f"), {tot['failing']} failing, {complete} of {len(s.files)} files complete, "
            f"{len(s.long)} lines of {STORY_LONG}+ lines, {len(s.stale)} stale table rows")


def cmd_build(ctx, a):
    b = build(ctx)
    s = build_story(ctx, b.glossary)
    if a.check:
        want = {ctx.path("master-en.tsv"): b.master_en, ctx.path("glossary.tsv"): b.glossary_text}
        if s is not None:
            want.update(story_outputs(ctx, s))
            extra = [p for p in list(ctx.path("story-en").glob("TS_*.tsv")) + [ctx.path("story-en") / "index.tsv"]
                     if p.exists() and p not in want]
        else:
            extra = []
        bad = [str(p.relative_to(ctx.data)) for p, text in want.items()
               if not p.exists() or p.read_text(encoding="utf-8") != text] + [str(p) for p in extra]
        if bad:
            print(f"stale: {', '.join(bad[:10])} (run tools/english_text.py build)", file=sys.stderr)
            return 1
        print("data/english is fresh: " + summary(b) + "\n" + story_summary(s))
        return 0
    write_build(ctx, b)
    if s is not None:
        write_story(ctx, s)
    print(summary(b) + "\n" + story_summary(s))
    return 0


def derive(ctx, out_dir):
    """The FULL resolved tables, official / memory / template included: master-en-full.tsv and
    story-en-full/TS_*.tsv (+ index.tsv), in the format of master-en.tsv. Not committed: the
    reference the server's C++ derivation (docs/english.md 7.6 "The derivation") is compared with."""
    out_dir = pathlib.Path(out_dir)
    b = build(ctx)
    write_if_changed(out_dir / "master-en-full.tsv", b.master_en_full)
    s = build_story(ctx, b.glossary)
    if s is not None:
        d = out_dir / "story-en-full"
        for stem, text in s.full_texts.items():
            write_if_changed(d / f"{stem}.tsv", text)
        for p in d.glob("TS_*.tsv"):
            if p.stem not in s.full_texts:
                p.unlink()
        write_if_changed(d / "index.tsv", s.index)
    return b, s


def cmd_derive(ctx, a):
    b, s = derive(ctx, a.out)
    print(f"{a.out}: master-en-full.tsv {len(b.out)} rows; " + story_summary(s))
    return 0


def rebuild(ctx, a):
    if not getattr(a, "no_build", False):
        b = build(ctx)
        write_build(ctx, b)
        s = build_story(ctx, b.glossary)
        if s is not None:
            write_story(ctx, s)
        print(summary(b) + "\n" + story_summary(s))


# ---------------------------------------------------------------- report

def report(ctx, b, out_dir):
    src, font = ctx.src, ctx.fnt
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    pref = collections.defaultdict(collections.Counter)
    for mid, k in b.klass.items():
        pref[C.prefix(mid)]["jp"] += 1
        if mid in b.out:
            pref[C.prefix(mid)][b.out[mid][2]] += 1
        elif k != "neutral":
            pref[C.prefix(mid)]["japanese"] += 1
    fail_kinds = collections.Counter()
    for f in b.failures:
        for k in f["problems"]:
            fail_kinds[(f["source"], k)] += 1
    served_fail = [f for f in b.failures if f["message_id"] not in b.out]
    leftover_tokens = [m for m, (_, e, _) in b.out.items() if C.GL_MARKUP.search(e)]
    g = src._english_glossary  # set by glossary_rows (build)
    conflicts = [(ja, t["en"], t["variants"]) for ja, t in g.items() if t["variants"]]
    sb = build_story(ctx, b.glossary)
    story, story_gaps = None, []
    if sb is not None:
        story_gaps = sb.derived.token_gaps
        groups = collections.defaultdict(collections.Counter)
        for stem, c in sb.files.items():
            g_ = groups[C.story_group(stem)]
            g_.update({k: c[k] for k in ("lines", "need", "english", "missing", "failing") + STORY_SOURCES})
            g_["files"] += 1
            g_["complete_files"] += c["english"] == c["need"]
        story = {"groups": {g_: dict(sorted(c.items())) for g_, c in sorted(groups.items())},
                 "complete_files": sum(c["complete_files"] for c in groups.values()),
                 "files": len(sb.files), f"lines_{STORY_LONG}_or_more": len(sb.long),
                 "budget_px": STORY_BUDGET, "stale_table_rows": len(sb.stale),
                 "table_rows": dict(collections.Counter(t["source"] for t in ctx.story_tables().values())),
                 "mt_rejected": len(read_tsv(ctx.work / "mt-rejected-story.tsv", REJECT_COLS))}
    gloss_warn = []
    for mid, (h, e, source) in sorted(b.out.items()):
        if source in DERIVED and mid in src.jp_rows:
            miss = C.glossary_misses(C.unesc(src.jp_rows[mid]), C.unesc(e), b.glossary)
            if miss:
                gloss_warn.append((mid, source, miss))
    rejected = read_tsv(ctx.work / "mt-rejected.tsv", REJECT_COLS)
    s = {
        "jp_master_rows": len(src.jp_rows),
        "candidates": {"official_by_id": b.candidates["official"], "official_e3": b.candidates["official_e3"],
                       "exact_memory": b.candidates["exact"], "exact_memory_ws": b.candidates["exact_ws"],
                       "template_memory": b.candidates["template"],
                       "neutral": b.candidates["neutral"], "gap": b.candidates["gap"],
                       "client_strings": b.candidates["client"]},
        "served": dict(sorted(b.served.items())),
        "served_total": len(b.out),
        "japanese_rows_left": sum(1 for m, k in b.klass.items() if k != "neutral" and m not in b.out),
        "failing_candidates": {f"{s_}/{k}": v for (s_, k), v in sorted(fail_kinds.items())},
        "failing_rows_left_japanese": len(served_fail),
        "served_rows_with_global_token": len(leftover_tokens),
        "token_rows_kept_japanese": len(b.token_gaps),
        "e3_rows": len(b.e3),
        "rebroken_lost_line_breaks": dict(b.rebroken),
        "width_outliers_single_line_over_1.5x": dict(collections.Counter(w[1] for w in b.width)),
        "q7_rows_older_global_english": len(b.q7),
        "matched_ws": dict(collections.Counter(b.matched.values())),
        "glossary_terms": len(b.glossary),
        "glossary_by_source": dict(collections.Counter(t["source"] for t in b.glossary.values())),
        "glossary_conflicts": len(conflicts),
        "glossary_warnings_derived_rows": len(gloss_warn),
        "human_overrides_of_official": len(b.overrides),
        "stale_table_rows": len(b.stale),
        "table_rows": dict(collections.Counter(t["source"] for t in b.table.values())),
        "mt_rejected": len(rejected),
        "story": story,
    }

    def w(name, cols, rows):
        with open(out_dir / name, "w", encoding="utf-8", newline="") as f:
            wr = csv.writer(f, delimiter="\t", lineterminator="\n")
            wr.writerow(cols)
            for r in rows:
                wr.writerow(r)
    w("prefixes.tsv", ["prefix", "jp_rows", "japanese_left"] + list(C_SOURCES),
      [[p, c["jp"], c["japanese"]] + [c[k] for k in C_SOURCES] for p, c in sorted(pref.items(), key=lambda x: -x[1]["jp"])])
    w("failing.tsv", ["message_id", "source", "served_instead", "problems", "en"],
      [[f["message_id"], f["source"], b.out.get(f["message_id"], ("", "", "japanese"))[2],
        json.dumps(f["problems"], ensure_ascii=False), f["en"]] for f in b.failures])
    w("width.tsv", ["message_id", "source", "ja_px", "en_px", "ratio", "ja", "en"],
      [[m, s_, wj, we, f"{we / max(wj, 1):.2f}", src.jp_rows[m], b.out[m][1]] for m, s_, wj, we in b.width])
    w("q7.tsv", ["message_id", "served_source", "ja", "global_old_ja", "global_en"],
      [[m, b.out.get(m, ("", "", "japanese"))[2], src.jp_rows[m], src.gl_ja.get(m), src.gl_en.get(m)] for m in b.q7])
    w("matched.tsv", ["message_id", "rule", "served_source", "ja", "global_ja", "served"],
      [[m, r, b.out.get(m, ("", "", "japanese"))[2], src.jp_rows[m], src.gl_ja.get(m) if r == "id-ws" else "",
        b.out.get(m, ("", "(failed a check)"))[1]] for m, r in sorted(b.matched.items())])
    w("token-gaps.tsv", ["message_id", "reason", "ja", "global_en"],
      [[m, why, ja, gen] for m, ja, gen, why in b.token_gaps] + [[m, why, ja, gen] for m, ja, gen, why in story_gaps])
    w("glossary-conflicts.tsv", ["ja", "en", "variants"], [[ja, en, " | ".join(v)] for ja, en, v in conflicts])
    w("glossary-warnings.tsv", ["message_id", "source", "missing_terms"],
      [[m, s_, json.dumps(x, ensure_ascii=False)] for m, s_, x in gloss_warn])
    w("overrides.tsv", ["message_id", "source", "official", "served"], b.overrides)
    w("stale.tsv", ["message_id", "source", "table_ja_sha1", "current_ja_sha1"], b.stale)
    w("e3.tsv", ["message_id", "ja", "global_en", "served"],
      [[m, src.jp_rows[m], src.gl_en[m], b.out.get(m, ("", "(failed a check)"))[1]] for m in b.e3])
    wide = [(m, s_, wj, we) for m, s_, wj, we in b.width_all if we > SCREEN_PX]
    w("wider-than-screen.tsv", ["message_id", "source", "ja_px", "en_px", "en"],
      [[m, s_, wj, we, b.out[m][1]] for m, s_, wj, we in wide])
    s["single_line_wider_than_screen"] = len(wide)
    boxes = box_rows(font, b.out, src.jp_rows)
    w("boxes.tsv", ["context", "message_id", "source", "ja_lines", "ja_px", "lines", "px", "lines_rebroken", "px_rebroken", "status", "en"], boxes)
    s["boxes"] = box_summary(boxes)
    hum = [(m, t) for m, t in sorted(b.table.items()) if t["source"] in HUMAN]
    w("human.tsv", ["message_id", "source", "editor", "ja", "served", "official", "note"],
      [[m, t["source"], t["editor"], src.jp_rows.get(m, ""), b.out[m][1] if m in b.out else "(failing)",
        Derived.of(ctx).official.get(m, ""), t["note"]] for m, t in hum])
    if sb is not None:
        cols = ["lines", "need", "english"] + list(STORY_SOURCES) + ["missing", "failing"]
        w("story-files.tsv", ["file", "group"] + cols + ["complete"],
          [[stem, C.story_group(stem)] + [c[k] for k in cols] + ["yes" if c["english"] == c["need"] else "no"]
           for stem, c in sorted(sb.files.items())])
        w("story-long.tsv", ["message_id", "file", "source", "lines", "en"], sb.long)
        w("story-failing.tsv", ["message_id", "file", "source", "served_instead", "problems", "en"],
          [[f["message_id"], f["file"], f["source"], sb.out.get(f["message_id"], ("", "", "japanese"))[2],
            json.dumps(f["problems"], ensure_ascii=False), f["en"]] for f in sb.failures])
        w("story-stale.tsv", ["message_id", "source", "table_ja_sha1", "current_ja_sha1"], sb.stale)
    (out_dir / "summary.json").write_text(json.dumps(s, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    return s


# Fixed text boxes per context (english.md 7.11): a label that takes its text's size (no IsCustomSize,
# so no shrink and no clip) inside a frame of fixed size. A served row needing more lines than the box
# has, or a wider line, overflows the frame. Informational (`report`: boxes.tsv); the build does not
# apply it yet.
#   home-talk  the home's speech box (UI/etc2/home.csf talk_menu_gp|talk_menu_talkmode/talk_frame/
#              talk_text: FontSize 24, placeholder 480x48 = two lines of 20 full-width characters,
#              anchored top-left 51 px into a 540x120 frame); CHome::PlayTalk @01aef4e8 sets it from
#              master_home_message rows and the Home3D rows' text_id, all *_hmmsg_* message ids
BOXES = {"home-talk": ("_hmmsg", 480, 2)}


def box_rows(font, out, jp_rows):
    """Per context of BOXES, the served rows: [context, message_id, source, ja_lines, ja_px, lines,
    px, lines_rebroken, px_rebroken (re-broken at the box width), status (fits | wide | tall), en]."""
    rows = []
    for ctx_name, (needle, px, nlines) in BOXES.items():
        for mid, (_h, e, source) in sorted(out.items()):
            if needle not in mid:
                continue
            en, ja = C.unesc(e), C.unesc(jp_rows.get(mid, ""))
            n, w = en.count("\n") + 1, font.widest(en)
            rb = font.rebreak(en, px)
            status = "fits" if n <= nlines and w <= px else "wide" if n <= nlines else "tall"
            rows.append([ctx_name, mid, source, ja.count("\n") + 1, font.widest(ja), n, w, rb.count("\n") + 1,
                         font.widest(rb), status, e])
    return rows


def box_summary(rows):
    s = {}
    for ctx_name, (_needle, px, nlines) in BOXES.items():
        r = [x for x in rows if x[0] == ctx_name]
        c = collections.Counter((x[2], x[9]) for x in r)
        s[ctx_name] = {"budget": f"{nlines} lines x {px} px", "rows": len(r),
                       "status": {f"{a}/{b}": v for (a, b), v in sorted(c.items())},
                       "fit_after_rebreak": sum(1 for x in r if x[7] <= nlines and x[8] <= px),
                       "lines_after_rebreak": dict(sorted(collections.Counter(x[7] for x in r).items()))}
    return s


# the client's design width (english.md 6.7): a single line wider than this at the font's 24 px wraps
# (labels, E10) or runs off the screen even in a full-width label; informational
SCREEN_PX = 720
C_SOURCES = ("official", "memory", "template", "machine", "agent", "human", "reviewed")


def cmd_report(ctx, a):
    b = build(ctx)
    s = report(ctx, b, a.out or ctx.work / "report")
    print(json.dumps(s, ensure_ascii=False, indent=1))
    print(f"lists: {a.out or ctx.work / 'report'}/", file=sys.stderr)
    return 0


# ---------------------------------------------------------------- show / set / review / stale

def cmd_show(ctx, a):
    b = build(ctx)
    src, font = ctx.src, ctx.fnt
    sb = build_story(ctx, b.glossary)
    for mid in a.ids:
        if sb is not None and mid in sb.derived.lines:
            stem, ja, h, klass, _ = sb.derived.lines[mid]
            print(f"== {mid}  (story {stem}, {C.story_group(stem)}, {klass})\nja        {C.esc(ja)}\n  sha1    {h}")
            if mid in src.gl_en:
                print(f"global en {src.gl_en.get(mid)}")
            t = ctx.story_tables().get(mid)
            if t:
                print("table     " + "  ".join(f"{k}={t[k]}" for k in TABLE_COLS[1:] if t[k]))
            o = sb.out.get(mid)
            print(f"served    [{o[2]}] {o[1]}" if o else "served    (Japanese)")
            for f in sb.failures:
                if f["message_id"] == mid:
                    print(f"failing   [{f['source']}] {json.dumps(f['problems'], ensure_ascii=False)}: {f['en']}")
            continue
        ja = src.jp_rows.get(mid)
        print(f"== {mid}  ({C.prefix(mid)}, {b.klass.get(mid, 'new id')})")
        if ja is not None:
            print(f"ja        {ja}\n  sha1    {C.sha1(ja)}  widest {font.widest(C.unesc(ja))} px")
        if mid in src.gl_en:
            print(f"global ja {src.gl_ja.get(mid)}\nglobal en {src.gl_en.get(mid)}")
        t = b.table.get(mid)
        if t:
            print("table     " + "  ".join(f"{k}={t[k]}" for k in TABLE_COLS[1:] if t[k]))
        if mid in b.out:
            h, e, s_ = b.out[mid]
            print(f"served    [{s_}] {e}\n  widest  {font.widest(C.unesc(e))} px")
        else:
            print("served    (Japanese)")
        for f in b.failures:
            if f["message_id"] == mid:
                print(f"failing   [{f['source']}] {json.dumps(f['problems'], ensure_ascii=False)}: {f['en']}")
        for m, ja_, gen, why in b.token_gaps:
            if m == mid:
                print(f"token gap {why}")
    return 0


def today():
    return datetime.date.today().isoformat()


def story_line(ctx, mid):
    """(file, Japanese with real newlines, sha1) of a story line, or None."""
    d = StoryDerived.of(ctx)
    if d is None or mid not in d.lines:
        return None
    stem, ja, h, _, _ = d.lines[mid]
    return stem, ja, h


def cmd_set(ctx, a):
    src = ctx.src
    sl = story_line(ctx, a.id)
    if sl is not None:
        text = a.text.replace("\r\n", "\n").replace("\n", "\\n")
        g = glossary_dict(glossary_rows(ctx))
        e, probs, _ = story_finish(ctx, g, a.source, text, sl[1])
        if probs and not a.force:
            print(f"{a.id}: {json.dumps(probs, ensure_ascii=False)} (fix the text or pass --force)", file=sys.stderr)
            return 1
        tables = ctx.story_tables()
        tables[a.id] = {"message_id": a.id, "ja_sha1": sl[2], "en": text, "source": a.source, "engine": "",
                        "date": a.date or today(), "editor": a.by, "note": a.note or "", "file": sl[0]}
        ctx.write_story_tables(tables)
        print(f"{a.id}: {a.source} story row ({sl[0]}) by {a.by}")
        rebuild(ctx, a)
        return 0
    table = ctx.table()
    ja = src.jp_rows.get(a.id)
    text = a.text.replace("\r\n", "\n").replace("\n", "\\n")
    g = glossary_dict(glossary_rows(ctx))
    e, probs, _ = finish(ctx, g, a.source, text, ja or "")
    if probs and not a.force:
        print(f"{a.id}: {json.dumps(probs, ensure_ascii=False)} (fix the text or pass --force)", file=sys.stderr)
        return 1
    table[a.id] = {"message_id": a.id, "ja_sha1": C.sha1(ja) if ja is not None else "", "en": text,
                   "source": a.source, "engine": "", "date": a.date or today(), "editor": a.by, "note": a.note or ""}
    ctx.write_table(table)
    print(f"{a.id}: {a.source} row by {a.by}" + (f" (problems: {json.dumps(probs, ensure_ascii=False)})" if probs else ""))
    rebuild(ctx, a)
    return 0


def cmd_review(ctx, a):
    table = ctx.table()
    stories = ctx.story_tables()
    rc = 0
    for mid in a.ids:
        t = table.get(mid) or stories.get(mid)
        if not t or t["source"] not in MACHINE:
            print(f"{mid}: no machine or agent row", file=sys.stderr)
            rc = 1
            continue
        t.update(source="reviewed", editor=a.by, date=a.date or today())
        print(f"{mid}: reviewed by {a.by}")
    ctx.write_table(table)
    ctx.write_story_tables(stories)
    rebuild(ctx, a)
    return rc


def cmd_stale(ctx, a):
    src = ctx.src
    n = 0
    for mid, t in sorted(ctx.table().items()):
        ja = src.jp_rows.get(mid)
        cur = C.sha1(ja) if ja is not None else ""
        if t["ja_sha1"] != cur or (ja is None and t["source"] not in HUMAN):
            n += 1
            print(f"{mid}\t{t['source']}\ttable {t['ja_sha1'] or '-'}\tnow {cur or '(not in the JP master)'}")
    d = StoryDerived.of(ctx)
    for mid, t in sorted(ctx.story_tables().items()):
        if d is None:
            break
        cur = d.lines[mid][2] if mid in d.lines else ""
        if t["ja_sha1"] != cur:
            n += 1
            print(f"{mid}\t{t['source']}\ttable {t['ja_sha1'] or '-'}\tnow {cur or '(not in the Scenario files)'}\t{t['file']}")
    if d is None:
        print("story tables not checked: no Scenario files", file=sys.stderr)
    print(f"{n} stale rows", file=sys.stderr)
    return 1 if n and a.fail else 0


# ---------------------------------------------------------------- PO and CSV round trips

def export_rows(ctx, b):
    """(mid, ja (master encoding) or "", served en, source) of every row to edit: JP rows with kana
    or kanji or with English, then the new message_ids."""
    src = ctx.src
    for mid in sorted(src.jp_rows):
        ja = src.jp_rows[mid] or ""
        if mid in b.out or C.has_kana(ja):
            o = b.out.get(mid)
            yield mid, ja, o[1] if o else "", o[2] if o else "japanese"
    for mid in sorted(set(b.out) - set(src.jp_rows)):
        yield mid, "", b.out[mid][1], b.out[mid][2]


def export_story_rows(ctx, sb):
    """(file, mid, ja (real newlines), served en (two-character \\n), source) of every story line
    with kana or kanji or with English; nothing without the Scenario files."""
    if sb is None:
        return
    d = sb.derived
    for stem in sorted(d.files):
        for mid in d.files[stem]:
            ja = d.lines[mid][1]
            o = sb.out.get(mid)
            if o or C.has_kana(ja):
                yield stem, mid, ja, o[1] if o else "", o[2] if o else "japanese"


def cmd_export_po(ctx, a):
    import polib  # only the PO round trip needs it
    b = build(ctx)
    src = ctx.src
    out = pathlib.Path(a.out or ctx.work / "po")
    out.mkdir(parents=True, exist_ok=True)
    files = {}
    for mid, ja, en, source in export_rows(ctx, b):
        p = C.prefix(mid)
        if p not in files:
            files[p] = polib.POFile(wrapwidth=0)
            files[p].metadata = {"Project-Id-Version": "soa-english", "Language": "en",
                                 "Content-Type": "text/plain; charset=UTF-8"}
        t = b.table.get(mid, {})
        comment = f"source: {source}" + (f"; engine: {t['engine']}" if t.get("engine") else "") + \
                  (f"; editor: {t['editor']}" if t.get("editor") else "")
        gl = src.gl_en.get(mid)
        extracted = f"Global: {gl}" if gl and gl != C.esc(C.unesc(en)) and not C.has_kana(gl) else ""
        files[p].append(polib.POEntry(msgctxt=mid, msgid=C.unesc(ja) or mid, msgstr=C.unesc(en),
                                      flags=["fuzzy"] if source == "machine" else [],
                                      tcomment=comment, comment=extracted))
    sb = build_story(ctx, b.glossary)
    stories = ctx.story_tables()
    for stem, mid, ja, en, source in export_story_rows(ctx, sb):
        if stem not in files:
            files[stem] = polib.POFile(wrapwidth=0)
            files[stem].metadata = {"Project-Id-Version": "soa-english", "Language": "en",
                                    "Content-Type": "text/plain; charset=UTF-8"}
        t = stories.get(mid, {})
        comment = f"source: {source}" + (f"; engine: {t['engine']}" if t.get("engine") else "") + \
                  (f"; editor: {t['editor']}" if t.get("editor") else "")
        gl = src.gl_en.get(mid)
        extracted = f"Global: {gl}" if gl and gl != en and not C.has_kana(gl) else ""
        files[stem].append(polib.POEntry(msgctxt=mid, msgid=ja or mid, msgstr=C.unesc(en),
                                         flags=["fuzzy"] if source == "machine" else [],
                                         tcomment=comment, comment=extracted))
    for p, po in sorted(files.items()):
        po.save(str(out / f"{p}.po"))
    print(f"{len(files)} .po files -> {out}")
    return 0


def apply_edits(ctx, a, edits):
    """edits: [(mid, ja as the editor saw it (real newlines) or None, english (real newlines), fuzzy)].
    A changed English becomes a human row; an unchanged machine row no longer fuzzy becomes reviewed."""
    b = build(ctx)
    src = ctx.src
    table = ctx.table()
    sb = build_story(ctx, b.glossary)
    stories = ctx.story_tables()
    n = collections.Counter()
    for mid, ja_seen, en, fuzzy in edits:
        sl = story_line(ctx, mid)
        if sl is not None:
            stem, ja, h = sl
            if ja_seen is not None and ja_seen != ja:
                n["stale (the Japanese changed)"] += 1
                continue
            if not en:
                continue
            en = C.esc(en.replace("\r\n", "\n"))
            cur = sb.out.get(mid)
            if cur and cur[1] == en:
                if cur[2] == "machine" and not fuzzy:
                    stories[mid].update(source="reviewed", editor=a.by, date=today())
                    n["story reviewed"] += 1
                continue
            stories[mid] = {"message_id": mid, "ja_sha1": h, "en": en, "source": "human", "engine": "",
                            "date": today(), "editor": a.by, "note": "", "file": stem}
            n["story human"] += 1
            continue
        ja = src.jp_rows.get(mid)
        if ja is not None and ja_seen is not None and ja_seen != C.unesc(ja):
            n["stale (the Japanese changed)"] += 1
            continue
        if not en:
            continue
        en = C.esc(en.replace("\r\n", "\n"))
        cur = b.out.get(mid)
        if cur and cur[1] == en:
            if cur[2] == "machine" and not fuzzy:
                table[mid].update(source="reviewed", editor=a.by, date=today())
                n["reviewed"] += 1
            continue
        if ja is None and mid not in b.out:
            n["unknown id"] += 1
            continue
        table[mid] = {"message_id": mid, "ja_sha1": C.sha1(ja) if ja is not None else "", "en": en,
                      "source": "human", "engine": "", "date": today(), "editor": a.by, "note": ""}
        n["human"] += 1
    ctx.write_table(table)
    ctx.write_story_tables(stories)
    print(dict(n))
    rebuild(ctx, a)
    return 0


def cmd_import_po(ctx, a):
    import polib
    edits = []
    for f in a.files:
        for e in polib.pofile(f):
            if e.msgctxt:
                ja = None if e.msgid == e.msgctxt else e.msgid
                edits.append((e.msgctxt, ja, e.msgstr, "fuzzy" in e.flags))
    return apply_edits(ctx, a, edits)


CSV_COLS = ["message_id", "source", "ja", "global_en", "en", "ja_px", "en_px", "problems"]


def cmd_export_csv(ctx, a):
    b = build(ctx)
    src, font = ctx.src, ctx.fnt
    fails = collections.defaultdict(list)
    for f in b.failures:
        fails[f["message_id"]].append(f"{f['source']}: {json.dumps(f['problems'], ensure_ascii=False)}")
    out = pathlib.Path(a.out or ctx.work / "english.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(CSV_COLS)
        for mid, ja, en, source in export_rows(ctx, b):
            gl = src.gl_en.get(mid, "")
            wr.writerow([mid, source, ja, gl if not C.has_kana(gl) else "", en,
                         font.widest(C.unesc(ja)), font.widest(C.unesc(en)) if en else "", "; ".join(fails[mid])])
        sb = build_story(ctx, b.glossary)
        if sb is not None:
            for f_ in sb.failures:
                fails[f_["message_id"]].append(f"{f_['source']}: {json.dumps(f_['problems'], ensure_ascii=False)}")
        for stem, mid, ja, en, source in export_story_rows(ctx, sb):
            gl = src.gl_en.get(mid, "")
            wr.writerow([mid, source, C.esc(ja), gl if not C.has_kana(gl) else "", en,
                         font.widest(ja, PLAYER_PX), font.widest(C.unesc(en), PLAYER_PX) if en else "",
                         "; ".join(fails[mid])])
    print(f"-> {out}")
    return 0


def cmd_import_csv(ctx, a):
    edits = []
    with open(a.file, encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            edits.append((r["message_id"], C.unesc(r["ja"]) if r.get("ja") else None, C.unesc(r.get("en") or ""), False))
    return apply_edits(ctx, a, edits)


# ---------------------------------------------------------------- import-mt

def read_labels(ctx):
    rows = read_tsv(ctx.path("labels.tsv"), LABEL_COLS)
    t = {}
    for r in rows:
        if r["ja"] in t:
            raise ValueError(f"labels.tsv: {r['ja']} twice")
        ok = (r["source"] == "derived" and not r["en"]) or (r["en"] and r["source"] in MACHINE + HUMAN)
        if not ok:
            raise ValueError(f"labels.tsv: {r['ja']}: source {r['source']!r} with en {r['en']!r}")
        t[r["ja"]] = r
    return t


def write_labels(ctx, t):
    write_if_changed(ctx.path("labels.tsv"), tsv_text(LABEL_COLS, [t[k] for k in sorted(t)]))


def label_problems(ctx, glossary, r):
    """The checks of a master row (english.md 7.9 step 6; tags strict for machine/agent) for a label's English."""
    _, probs, _ = finish(ctx, glossary, r["source"], r["en"], r["ja"])
    return probs


def cmd_labels(ctx, a):
    t = read_labels(ctx)
    g = glossary_dict(glossary_rows(ctx))
    bad = 0
    for ja in sorted(t):
        r = t[ja]
        if r["source"] == "derived":
            continue
        probs = label_problems(ctx, g, r)
        if probs:
            bad += 1
            print(f"{ja}: {json.dumps(probs, ensure_ascii=False)}", file=sys.stderr)
    text = tsv_text(LABEL_COLS, [t[k] for k in sorted(t)])
    stale = ctx.path("labels.tsv").read_text(encoding="utf-8") != text
    if stale:
        print("labels.tsv: not in the canonical form (sorted by ja); run without --check to rewrite", file=sys.stderr)
        if not a.check:
            write_labels(ctx, t)
    n = collections.Counter(r["source"] for r in t.values())
    print(json.dumps(dict(sorted(n.items()))), f"{bad} failing")
    return 1 if bad or (stale and a.check) else 0


def cmd_label_set(ctx, a):
    t = read_labels(ctx)
    ja = a.ja.replace("\r\n", "\n").replace("\n", "\\n")
    if ja not in t:
        print(f"{ja}: not a row of labels.tsv (add the label first)", file=sys.stderr)
        return 1
    text = a.text.replace("\r\n", "\n").replace("\n", "\\n")
    r = {"ja": ja, "en": text, "source": a.source, "engine": "", "date": a.date or today(), "editor": a.by, "note": a.note or ""}
    probs = label_problems(ctx, glossary_dict(glossary_rows(ctx)), r)
    if probs and not a.force:
        print(f"{ja}: {json.dumps(probs, ensure_ascii=False)} (fix the text or pass --force)", file=sys.stderr)
        return 1
    t[ja] = r
    write_labels(ctx, t)
    print(f"{ja}: {a.source} label row by {a.by}")
    return 0


def import_mt_labels(ctx, a, rows, n):
    t = read_labels(ctx)
    g = glossary_dict(glossary_rows(ctx))
    font = ctx.fnt
    rej_path = ctx.work / "mt-rejected-labels.tsv"
    rejected = {}
    for r in rows:
        ja = r["ja"]
        cur = t.get(ja)
        if cur is None:
            n["label: not in labels.tsv"] += 1
            continue
        if cur["source"] in HUMAN or (cur["source"] in MACHINE and not a.replace):
            n["label: kept " + cur["source"]] += 1
            continue
        jn = C.unesc(ja)
        en, probs = C.post_one({"ja": ja, "budget": font.widest(jn), "multiline": "\n" in jn}, r["mt"], font, g)
        probs.pop("width", None)
        row = {"ja": ja, "en": C.esc(en), "source": "machine", "engine": engine_name(r), "date": r.get("date", ""),
               "editor": "", "note": ""}
        if not probs:
            probs = label_problems(ctx, g, row)
        if probs:
            rejected[ja] = {"message_id": ja, "ja_sha1": C.sha1(ja), "engine": row["engine"], "date": row["date"],
                            "en": row["en"], "problems": json.dumps(probs, ensure_ascii=False)}
            n["label: rejected"] += 1
            continue
        t[ja] = row
        n["label: imported"] += 1
    write_labels(ctx, t)
    if rejected:
        rej_path.parent.mkdir(parents=True, exist_ok=True)
        rej_path.write_text(tsv_text(REJECT_COLS, [rejected[k] for k in sorted(rejected)]), encoding="utf-8")
        print(f"rejected labels: {rej_path}", file=sys.stderr)


def engine_name(r):
    return f"{r['model']}/{r['quant']}/{r['prompt']}/llama.cpp-{r['llama_build']}/t{r['temperature']}"


def cmd_import_mt(ctx, a):
    n = collections.Counter()
    with open(a.checkpoint, encoding="utf-8") as f:
        lines = [json.loads(x) for x in f if x.strip()]
    label_rows = [r for r in lines if r.get("kind") == "label"]
    if label_rows:  # layout labels: labels.tsv only (english.md 7.14)
        import_mt_labels(ctx, a, label_rows, n)
        print(json.dumps(dict(sorted(n.items())), ensure_ascii=False))
        return 0
    b = build(ctx)
    src, font = ctx.src, ctx.fnt
    table = ctx.table()
    rej_path = ctx.work / "mt-rejected.tsv"
    rejected = {r["message_id"]: r for r in read_tsv(rej_path, REJECT_COLS)}
    def is_story(r):
        return r.get("kind") == "story" or "lines" in r
    story_rows = [r for r in lines if is_story(r)]
    if story_rows:
        import_mt_story(ctx, a, b, story_rows, n)
    for r in lines:
        if is_story(r):
            continue
        engine = engine_name(r)
        for mid in r["ids"]:
            ja = src.jp_rows.get(mid)
            if ja is None:
                n["not in the JP master"] += 1
                continue
            h = C.sha1(ja)
            if r["ja_sha1"] != h:
                n["hash mismatch"] += 1
                continue
            t = table.get(mid)
            if t and t["source"] in HUMAN:
                n["kept: human/reviewed"] += 1
                continue
            served = b.out.get(mid)
            if served and served[2] in DERIVED + HUMAN:
                n["kept: covered by " + served[2]] += 1
                continue
            if t and t["source"] == "machine":
                if not a.replace:
                    n["kept: machine row exists"] += 1
                    continue
                if t["ja_sha1"] == h and t["engine"] == engine:
                    n["kept: same hash, engine and prompt"] += 1
                    continue
            jn = C.unesc(ja)
            row = {"ja": ja, "budget": font.widest(jn), "multiline": "\n" in jn}
            en, probs = C.post_one(row, r["mt"], font, b.glossary)
            probs.pop("width", None)  # single-line width is reported, not failed (the client wraps, E10)
            if not probs:
                _, probs, _ = finish(ctx, b.glossary, "machine", C.esc(en), ja)
            if probs:
                rejected[mid] = {"message_id": mid, "ja_sha1": h, "engine": engine, "date": r.get("date", ""),
                                 "en": C.esc(en), "problems": json.dumps(probs, ensure_ascii=False)}
                n["rejected"] += 1
                continue
            rejected.pop(mid, None)
            table[mid] = {"message_id": mid, "ja_sha1": h, "en": C.esc(en), "source": "machine",
                          "engine": engine, "date": r.get("date", ""), "editor": "", "note": ""}
            n["imported"] += 1
    ctx.write_table(table)
    if rejected or rej_path.exists():
        rej_path.parent.mkdir(parents=True, exist_ok=True)
        rej_path.write_text(tsv_text(REJECT_COLS, [rejected[m] for m in sorted(rejected)]), encoding="utf-8")
    print(json.dumps(dict(sorted(n.items())), ensure_ascii=False))
    if n["rejected"]:
        print(f"rejected rows: {rej_path}", file=sys.stderr)
    rebuild(ctx, a)
    return 0


def import_mt_story(ctx, a, b, rows, n):
    """The story checkpoint (english_mt_run.py story): per line message_id, file, ja_sha1 (of the
    text_value with real newlines), mt (one line of English, or null when the model skipped it)."""
    s = build_story(ctx, b.glossary)
    if s is None:
        sys.exit("import-mt: story rows need the Scenario files (work/SOA-3.7.0-canonical-data.zip)")
    d = s.derived
    tables = ctx.story_tables()
    rej_path = ctx.work / "mt-rejected-story.tsv"
    rejected = {r["message_id"]: r for r in read_tsv(rej_path, REJECT_COLS)}
    for r in rows:
        engine = engine_name(r)
        for ln in r["lines"]:
            mid = ln["message_id"]
            if mid not in d.lines:
                n["story: not in the Scenario files"] += 1
                continue
            stem, ja, h, klass, _ = d.lines[mid]
            if ln["ja_sha1"] != h:
                n["story: hash mismatch"] += 1
                continue
            t = tables.get(mid)
            if t and t["source"] in HUMAN:
                n["story kept: human/reviewed"] += 1
                continue
            served = s.out.get(mid)
            if served and served[2] in DERIVED + HUMAN:
                n["story kept: covered by " + served[2]] += 1
                continue
            if not ln.get("mt"):
                n["story: skipped by the model"] += 1
                continue
            if t and t["source"] == "machine":
                if not a.replace:
                    n["story kept: machine row exists"] += 1
                    continue
                if t["ja_sha1"] == h and t["engine"] == engine:
                    n["story kept: same hash, engine and prompt"] += 1
                    continue
            e, probs, _ = story_finish(ctx, b.glossary, "machine", C.esc(ln["mt"]), ja)
            if probs:
                rejected[mid] = {"message_id": mid, "ja_sha1": h, "engine": engine, "date": r.get("date", ""),
                                 "en": e, "problems": json.dumps(probs, ensure_ascii=False)}
                n["story rejected"] += 1
                continue
            rejected.pop(mid, None)
            tables[mid] = {"message_id": mid, "ja_sha1": h, "en": e, "source": "machine", "engine": engine,
                           "date": r.get("date", ""), "editor": "", "note": "", "file": stem}
            n["story imported"] += 1
    ctx.write_story_tables(tables)
    if rejected or rej_path.exists():
        rej_path.parent.mkdir(parents=True, exist_ok=True)
        rej_path.write_text(tsv_text(REJECT_COLS, [rejected[m] for m in sorted(rejected)]), encoding="utf-8")
    if n["story rejected"]:
        print(f"rejected story lines: {rej_path}", file=sys.stderr)


# ---------------------------------------------------------------- main

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", default=str(DATA))
    ap.add_argument("--master", default=str(C.MASTER_DB))
    ap.add_argument("--gl", default=str(C.GLOBAL_DB))
    ap.add_argument("--scenario", default=str(C.SCENARIO),
                    help="the Scenario files: the 3.7.0 download (default its zip work/SOA-3.7.0-canonical-data.zip, read in place; "
                         "or a folder) or a folder of TS_*.msgp")
    ap.add_argument("--font", default=None, help="font.fpk, an .apk, or a glyphs .pkl (default: the committed APK)")
    ap.add_argument("--work", default=str(WORK))
    ap.add_argument("--no-build", action="store_true", help="edits: don't rebuild master-en.tsv afterwards")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("build")
    p.add_argument("--check", action="store_true")
    p = sub.add_parser("report")
    p.add_argument("--out")
    p = sub.add_parser("show")
    p.add_argument("ids", nargs="+")
    p = sub.add_parser("set")
    p.add_argument("id")
    p.add_argument("text")
    p.add_argument("--by", required=True)
    p.add_argument("--note")
    p.add_argument("--date")
    p.add_argument("--force", action="store_true")
    p.add_argument("--source", choices=("human", "agent"), default="human",
                   help="agent: an AI agent wrote it (ranked like machine; --by names the agent)")
    p = sub.add_parser("review")
    p.add_argument("ids", nargs="+")
    p.add_argument("--by", required=True)
    p.add_argument("--date")
    p = sub.add_parser("stale")
    p.add_argument("--fail", action="store_true", help="exit 1 when any row is stale")
    p = sub.add_parser("export-po")
    p.add_argument("--out")
    p = sub.add_parser("import-po")
    p.add_argument("files", nargs="+")
    p.add_argument("--by", required=True)
    p = sub.add_parser("export-csv")
    p.add_argument("--out")
    p = sub.add_parser("import-csv")
    p.add_argument("file")
    p.add_argument("--by", required=True)
    p = sub.add_parser("derive")
    p.add_argument("--out", required=True)
    p = sub.add_parser("glossary-weak")
    p.add_argument("--apply", action="store_true", help="add the human rows that remove the weak terms")
    p = sub.add_parser("labels")
    p.add_argument("--check", action="store_true")
    p = sub.add_parser("label-set")
    p.add_argument("ja")
    p.add_argument("text")
    p.add_argument("--by", required=True)
    p.add_argument("--note")
    p.add_argument("--date")
    p.add_argument("--force", action="store_true")
    p.add_argument("--source", choices=("human", "agent"), default="human",
                   help="agent: an AI agent wrote it (ranked like machine; --by names the agent)")
    p = sub.add_parser("import-mt")
    p.add_argument("checkpoint")
    p.add_argument("--replace", action="store_true",
                   help="replace machine rows whose hash, engine or prompt changed")
    a = ap.parse_args(argv)
    ctx = Ctx(a.data, a.master, a.gl, a.scenario, a.font, a.work)
    cmds = {"build": cmd_build, "report": cmd_report, "show": cmd_show, "set": cmd_set, "review": cmd_review,
            "stale": cmd_stale, "export-po": cmd_export_po, "import-po": cmd_import_po,
            "export-csv": cmd_export_csv, "import-csv": cmd_import_csv, "import-mt": cmd_import_mt,
            "glossary-weak": cmd_glossary_weak, "derive": cmd_derive,
            "labels": cmd_labels, "label-set": cmd_label_set}
    return cmds[a.cmd](ctx, a)


if __name__ == "__main__":
    sys.exit(main())
