#!/usr/bin/env python3
"""The English text table: build, report and edit (docs/english.md 7.6, PLAN-english.md E1/M1/E3).

Files (data/english/, committed):
  master.tsv          the rows a person or an engine wrote: message_id, ja_sha1, en, source
                      (machine | human | reviewed), engine, date, editor, note. Official, memory and
                      template English is NOT stored: the build derives it from the two master DBs.
  glossary.tsv        ja, en, kind, variants, source (official | human | machine), note. The official
                      rows are regenerated by `build` from Global (Q8); human and machine rows are kept.
  client-strings.tsv  message_id, en, note: the client's new strings (port_en_*), merged as human
                      rows with an empty ja_sha1.
  master-en.tsv       GENERATED by `build`: message_id, ja_sha1, en, source; every row that ends up
                      English after the checks, sorted by message_id. The server serves exactly this.
All TSVs: UTF-8, a header line, no quoting, a line break inside a text is the two characters \\n.

Precedence per message_id (english.md 7.6): human/reviewed > official (Global by id, the five
filters; plus Global token rows rewritten by E3) > memory (exact) / template > machine > Japanese.
A candidate that fails a check (english.md 7.5) is not served; the next one is tried, and the failure
is listed by `report`. A table row whose ja_sha1 differs from the current Japanese is stale: not served.

Usage:
  tools/english_text.py build [--check]          write master-en.tsv and glossary.tsv's official rows
                                                 (--check: exit 1 when the committed files are stale)
  tools/english_text.py report [--out DIR]       coverage per source and prefix, failing rows, width
                                                 outliers, Q7 rows, token gaps, glossary conflicts
                                                 (summary to stdout, lists to work/english/report/)
  tools/english_text.py show ID
  tools/english_text.py set ID TEXT --by NAME [--note N] [--force]
  tools/english_text.py review ID... --by NAME   machine -> reviewed (kept unchanged)
  tools/english_text.py stale                    table rows whose Japanese changed
  tools/english_text.py export-po [--out DIR]    one .po per prefix (work/english/po/)
  tools/english_text.py import-po FILE... --by NAME
  tools/english_text.py export-csv [--out FILE]  (work/english/english.csv)
  tools/english_text.py import-csv FILE --by NAME
  tools/english_text.py import-mt CHECKPOINT.jsonl [--replace]
                                                 machine rows from the MT runner's checkpoint; rows
                                                 failing the checks go to work/english/mt-rejected.tsv
Common options: --data DIR (data/english) --master DB --gl DB --scenario DIR --font FILE --no-build
"""
import argparse
import collections
import csv
import datetime
import json
import pathlib
import sys
import unicodedata

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))

import english_core as C  # noqa: E402

DATA = REPO / "data/english"
WORK = REPO / "work/english"
TABLE_COLS = ["message_id", "ja_sha1", "en", "source", "engine", "date", "editor", "note"]
GLOSSARY_COLS = ["ja", "en", "kind", "variants", "source", "note"]
CLIENT_COLS = ["message_id", "en", "note"]
OUT_COLS = ["message_id", "ja_sha1", "en", "source"]
REJECT_COLS = ["message_id", "ja_sha1", "engine", "date", "en", "problems"]
HUMAN = ("human", "reviewed")
DERIVED = ("official", "memory", "template")
GLOSSARY_RANK = {"human": 0, "official": 1, "machine": 2}


# ---------------------------------------------------------------- TSV files

def _field(s):
    s = "" if s is None else str(s)
    if any(c in s for c in "\t\r\n"):
        raise ValueError(f"tab or line break in a field: {s!r}")
    return s


def tsv_text(cols, rows):
    out = ["\t".join(cols)]
    for r in rows:
        out.append("\t".join(_field(r.get(c, "")) for c in cols))
    return "\n".join(out) + "\n"


def read_tsv(path, cols, required=False):
    """[{col: value}] of a TSV with exactly this header; [] for a missing file unless required."""
    path = pathlib.Path(path)
    if not path.exists():
        if required:
            raise FileNotFoundError(path)
        return []
    lines = path.read_text(encoding="utf-8").split("\n")
    if lines and lines[-1] == "":
        lines.pop()
    if not lines or lines[0].split("\t") != cols:
        raise ValueError(f"{path}: header must be {cols}")
    rows = []
    for n, line in enumerate(lines[1:], 2):
        f = line.split("\t")
        if len(f) != len(cols):
            raise ValueError(f"{path}:{n}: {len(f)} fields, want {len(cols)}")
        rows.append(dict(zip(cols, f)))
    return rows


def write_if_changed(path, text):
    path = pathlib.Path(path)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


_SOURCES = {}  # read-only sources, shared by the commands of one process (the tests)


class Ctx:
    def __init__(self, data=DATA, master=C.MASTER_DB, gl=C.GLOBAL_DB, scenario=C.SCENARIO_DIR, font=None,
                 work=WORK):
        self.data = pathlib.Path(data)
        self.master, self.gl, self.scenario, self.font = master, gl, scenario, font
        self.work = pathlib.Path(work)
        self._src = self._font = None

    @property
    def src(self):
        if self._src is None:
            key = (str(self.master), str(self.gl), str(self.scenario))
            if key not in _SOURCES:
                _SOURCES[key] = C.Sources(master=self.master, gl=self.gl, scenario=self.scenario)
            self._src = _SOURCES[key]
        return self._src

    @property
    def fnt(self):
        if self._font is None:
            self._font = C.Font(self.font)
        return self._font

    def path(self, name):
        return self.data / name

    def table(self):
        rows = read_tsv(self.path("master.tsv"), TABLE_COLS)
        t = {}
        for r in rows:
            if r["message_id"] in t:
                raise ValueError(f"master.tsv: {r['message_id']} twice")
            if r["source"] not in ("machine",) + HUMAN:
                raise ValueError(f"master.tsv: {r['message_id']}: source {r['source']!r} (machine|human|reviewed)")
            t[r["message_id"]] = r
        return t

    def write_table(self, t):
        rows = [t[m] for m in sorted(t)]
        write_if_changed(self.path("master.tsv"), tsv_text(TABLE_COLS, rows))


# ---------------------------------------------------------------- glossary

def glossary_rows(ctx):
    """glossary.tsv's rows: Global's terms regenerated, the human and machine rows of the file kept."""
    src = ctx.src
    if not hasattr(src, "_english_glossary"):
        src._english_glossary = C.build_glossary(src)
    official = src._english_glossary
    rows = [{"ja": ja, "en": t["en"], "kind": t["kind"], "variants": " | ".join(t["variants"]),
             "source": "official", "note": ""} for ja, t in official.items()]
    for r in read_tsv(ctx.path("glossary.tsv"), GLOSSARY_COLS):
        if r["source"] == "official":
            continue
        if r["source"] not in GLOSSARY_RANK:
            raise ValueError(f"glossary.tsv: {r['ja']}: source {r['source']!r} (official|human|machine)")
        rows.append(r)
    rows.sort(key=lambda r: (r["ja"], GLOSSARY_RANK[r["source"]], r["en"]))
    return rows


def glossary_dict(rows):
    """{ja: {"en", "variants", "kind", "source"}}: per term the human row, else the official, else the
    machine one (M2's new names). A row with an empty en removes the term."""
    best = {}
    for r in rows:
        cur = best.get(r["ja"])
        if cur is None or GLOSSARY_RANK[r["source"]] < GLOSSARY_RANK[cur["source"]]:
            best[r["ja"]] = r
    return {ja: {"en": r["en"], "variants": [v for v in r["variants"].split(" | ") if v],
                 "kind": r["kind"], "source": r["source"]}
            for ja, r in sorted(best.items()) if r["en"]}


# ---------------------------------------------------------------- build

class Built:
    pass


def finish(ctx, glossary, source, en, ja):
    """(served English in the master encoding, problems) of one candidate for a JP row (`ja` in the
    master encoding; "" for a new message_id). Folding, %% in printf rows, and for derived rows a
    re-break when Global dropped the Japanese row's line breaks (english.md 3.2: the 459 rows);
    Global's own line breaks are kept."""
    font = ctx.fnt
    jn = C.unesc(ja)
    e = C.unesc(en)
    if source in HUMAN:
        e = unicodedata.normalize("NFC", e)
    e = font.fold(e)
    e = C.fix_percent(e, ja)
    rebroken = False
    if source in DERIVED and "\n" in jn and "\n" not in e:
        e = font.rebreak(e, max(font.widest(jn), 200))
        rebroken = True
    if not ja:  # a new message_id (client strings): no Japanese to compare tokens with
        probs = C.check(e, e, font)
    else:
        probs = C.check(jn, e, font, glossary if source not in DERIVED else None,
                        tags="strict" if source == "machine" else "subset")
    return C.esc(e), probs, rebroken


class Derived:
    """The part of a build that depends only on the master DBs and the font: per JP row its class
    and its official / memory / template candidate, already finished and checked. Cached per Sources
    (they are read-only), so the edit commands and the tests rebuild quickly."""

    def __init__(self, ctx):
        src, font = ctx.src, ctx.fnt
        mem = C.Memory(src)
        self.rows = {}        # mid -> (ja, sha1, klass, [(source, en, probs, rebroken, (ja px, en px) or None)])
        self.e3, self.token_gaps, self.q7 = [], [], []
        self.official = {}    # mid -> Global's English as stored (for the human override list)
        for mid in sorted(src.jp_rows):
            ja = src.jp_rows[mid] or ""
            jn = C.unesc(ja)
            cands = []
            off = src.official(mid, ja)
            klass = None
            if off is not None:
                klass = "official"
                cands.append(("official", off))
            else:
                e3, why = src.official_e3(mid, ja)
                if e3 is not None:
                    klass = "official_e3"
                    self.e3.append(mid)
                    cands.append(("official", e3))
                elif why:
                    self.token_gaps.append((mid, ja, src.gl_en[mid], why))
            if klass is None:
                if not C.has_kana(ja):
                    klass = "neutral"
                else:
                    m, kind = mem.lookup(ja)
                    if m is not None:
                        klass = kind
                        cands.append(("memory" if kind == "exact" else "template", m))
                    else:
                        klass = "gap"
            if cands and cands[0][0] == "official":
                self.official[mid] = cands[0][1]
            if C.has_kana(ja) and src.gl_english(mid) and src.gl_ja.get(mid) != ja:
                self.q7.append(mid)  # Global's English translates an older Japanese text (Q7)
            done = []
            for source, en in cands:
                e, probs, rebroken = finish(ctx, None, source, en, ja)
                done.append((source, e, probs, rebroken, widths(font, jn, C.unesc(e))))
            self.rows[mid] = (ja, C.sha1(ja), klass, done)

    @staticmethod
    def of(ctx):
        cache = ctx.src.__dict__.setdefault("_english_derived", {})
        key = str(ctx.font)
        if key not in cache:
            cache[key] = Derived(ctx)
        return cache[key]


def widths(font, jn, en):
    """(ja px, en px) of a single-line row, else None."""
    if "\n" in jn or "\n" in en:
        return None
    return font.widest(jn), font.widest(en)


def build(ctx):
    """Everything `build` and `report` need, computed in memory."""
    src, font = ctx.src, ctx.fnt
    d = Derived.of(ctx)
    g_rows = glossary_rows(ctx)
    glossary = glossary_dict(g_rows)
    table = ctx.table()
    client = read_tsv(ctx.path("client-strings.tsv"), CLIENT_COLS)
    b = Built()
    b.glossary_rows, b.glossary = g_rows, glossary
    b.table = table
    b.out = {}            # mid -> (ja_sha1, en, source)
    b.klass = {}          # mid -> official | official_e3 | exact | template | neutral | gap
    b.candidates = collections.Counter()
    b.served = collections.Counter()
    b.failures = []       # {message_id, source, en, problems}
    b.token_gaps = d.token_gaps  # (mid, ja, gl_en, reason)
    b.stale = []          # (mid, source, table sha1, current sha1)
    b.width = []          # (mid, source, ja px, en px)
    b.overrides = []      # (mid, source, official en, served en)
    b.rebroken = collections.Counter()
    b.e3, b.q7 = d.e3, d.q7
    for mid, (ja, h, klass, derived) in d.rows.items():
        cands = []
        t = table.get(mid)
        if t and t["ja_sha1"] != h:
            b.stale.append((mid, t["source"], t["ja_sha1"], h))
            t = None
        if t and t["source"] in HUMAN:
            cands.append((t["source"], t["en"]))
        cands += derived
        if t and t["source"] == "machine":
            cands.append(("machine", t["en"]))
        b.klass[mid] = klass
        b.candidates[klass] += 1
        for c in cands:
            if len(c) == 2:  # a table row: finish it now (the glossary may have changed)
                source = c[0]
                e, probs, rebroken = finish(ctx, glossary, source, c[1], ja)
                w = widths(font, C.unesc(ja), C.unesc(e))
            else:
                source, e, probs, rebroken, w = c
            if probs:
                b.failures.append({"message_id": mid, "source": source, "en": e, "problems": probs})
                continue
            b.out[mid] = (h, e, source)
            b.served[source] += 1
            if rebroken:
                b.rebroken[source] += 1
            off = d.official.get(mid)
            if source in HUMAN and off is not None and C.esc(C.unesc(off)) != e:
                b.overrides.append((mid, source, off, e))
            if w and w[1] > 1.5 * max(w[0], 100):
                b.width.append((mid, source, w[0], w[1]))
            break
    # new message_ids: master.tsv human rows without a JP row, then the client's strings
    extra = {}
    for r in client:
        extra[r["message_id"]] = ("human", r["en"])
    for mid, t in sorted(table.items()):
        if mid in src.jp_rows:
            continue
        if t["ja_sha1"] or t["source"] not in HUMAN:
            b.stale.append((mid, t["source"], t["ja_sha1"], ""))
            continue
        extra[mid] = (t["source"], t["en"])
    for mid in sorted(extra):
        source, en = extra[mid]
        if mid in src.jp_rows:
            b.failures.append({"message_id": mid, "source": source, "en": en,
                               "problems": {"id": "a client string's id is a JP master message_id"}})
            continue
        e, probs, _ = finish(ctx, glossary, source, en, "")
        if probs:
            b.failures.append({"message_id": mid, "source": source, "en": e, "problems": probs})
            continue
        b.out[mid] = ("", e, source)
        b.served[source] += 1
        b.candidates["client"] += 1
    rows = [{"message_id": m, "ja_sha1": b.out[m][0], "en": b.out[m][1], "source": b.out[m][2]}
            for m in sorted(b.out, key=lambda m: m.encode())]
    b.master_en = tsv_text(OUT_COLS, rows)
    b.glossary_text = tsv_text(GLOSSARY_COLS, g_rows)
    return b


def write_build(ctx, b):
    ch = write_if_changed(ctx.path("master-en.tsv"), b.master_en)
    ch |= write_if_changed(ctx.path("glossary.tsv"), b.glossary_text)
    if not ctx.path("client-strings.tsv").exists():
        write_if_changed(ctx.path("client-strings.tsv"), tsv_text(CLIENT_COLS, []))
    return ch


def summary(b):
    return (f"{len(b.out)} rows English: " + ", ".join(f"{k} {v}" for k, v in sorted(b.served.items()))
            + f"; {len(b.failures)} failing candidates, {len(b.stale)} stale table rows")


def cmd_build(ctx, a):
    b = build(ctx)
    if a.check:
        bad = [n for n, text in (("master-en.tsv", b.master_en), ("glossary.tsv", b.glossary_text))
               if not ctx.path(n).exists() or ctx.path(n).read_text(encoding="utf-8") != text]
        if bad:
            print(f"stale: {', '.join(bad)} (run tools/english_text.py build)", file=sys.stderr)
            return 1
        print("data/english is fresh: " + summary(b))
        return 0
    write_build(ctx, b)
    print(summary(b))
    return 0


def rebuild(ctx, a):
    if not getattr(a, "no_build", False):
        b = build(ctx)
        write_build(ctx, b)
        print(summary(b))


# ---------------------------------------------------------------- report

def story_coverage(ctx):
    """Story lines (kana or kanji) per group: official (Global by id), official after E3, gap."""
    src = ctx.src
    if not src.scenario_dir.is_dir():
        return None, []
    n = collections.Counter()
    gaps = []
    for stem, mid, ja in src.story():
        if not C.has_kana(ja):
            continue
        g = C.story_group(stem)
        if src.story_official(mid, ja):
            n[(g, "official")] += 1
            continue
        e3, why = src.story_official_e3(mid, ja)
        if e3 is not None:
            n[(g, "official_e3")] += 1
        else:
            n[(g, "gap")] += 1
            if why:
                gaps.append((mid, C.esc(ja), src.gl_en.get(mid, ""), why))
    return {f"{g}/{k}": v for (g, k), v in sorted(n.items())}, gaps


def report(ctx, b, out_dir):
    src, font = ctx.src, ctx.fnt
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    pref = collections.defaultdict(collections.Counter)
    for mid, k in b.klass.items():
        pref[C.prefix(mid)]["jp"] += 1
        if mid in b.out:
            pref[C.prefix(mid)][b.out[mid][2]] += 1
        elif k != "neutral":
            pref[C.prefix(mid)]["japanese"] += 1
    fail_kinds = collections.Counter()
    for f in b.failures:
        for k in f["problems"]:
            fail_kinds[(f["source"], k)] += 1
    served_fail = [f for f in b.failures if f["message_id"] not in b.out]
    leftover_tokens = [m for m, (_, e, _) in b.out.items() if C.GL_MARKUP.search(e)]
    g = src._english_glossary  # set by glossary_rows (build)
    conflicts = [(ja, t["en"], t["variants"]) for ja, t in g.items() if t["variants"]]
    story, story_gaps = story_coverage(ctx)
    gloss_warn = []
    for mid, (h, e, source) in sorted(b.out.items()):
        if source in DERIVED and mid in src.jp_rows:
            miss = C.glossary_misses(C.unesc(src.jp_rows[mid]), C.unesc(e), b.glossary)
            if miss:
                gloss_warn.append((mid, source, miss))
    rejected = read_tsv(ctx.work / "mt-rejected.tsv", REJECT_COLS)
    s = {
        "jp_master_rows": len(src.jp_rows),
        "candidates": {"official_by_id": b.candidates["official"], "official_e3": b.candidates["official_e3"],
                       "exact_memory": b.candidates["exact"], "template_memory": b.candidates["template"],
                       "neutral": b.candidates["neutral"], "gap": b.candidates["gap"],
                       "client_strings": b.candidates["client"]},
        "served": dict(sorted(b.served.items())),
        "served_total": len(b.out),
        "japanese_rows_left": sum(1 for m, k in b.klass.items() if k != "neutral" and m not in b.out),
        "failing_candidates": {f"{s_}/{k}": v for (s_, k), v in sorted(fail_kinds.items())},
        "failing_rows_left_japanese": len(served_fail),
        "served_rows_with_global_token": len(leftover_tokens),
        "token_rows_kept_japanese": len(b.token_gaps),
        "e3_rows": len(b.e3),
        "rebroken_lost_line_breaks": dict(b.rebroken),
        "width_outliers_single_line_over_1.5x": dict(collections.Counter(w[1] for w in b.width)),
        "q7_rows_older_global_english": len(b.q7),
        "glossary_terms": len(b.glossary),
        "glossary_by_source": dict(collections.Counter(t["source"] for t in b.glossary.values())),
        "glossary_conflicts": len(conflicts),
        "glossary_warnings_derived_rows": len(gloss_warn),
        "human_overrides_of_official": len(b.overrides),
        "stale_table_rows": len(b.stale),
        "table_rows": dict(collections.Counter(t["source"] for t in b.table.values())),
        "mt_rejected": len(rejected),
        "story": story,
    }

    def w(name, cols, rows):
        with open(out_dir / name, "w", encoding="utf-8", newline="") as f:
            wr = csv.writer(f, delimiter="\t", lineterminator="\n")
            wr.writerow(cols)
            for r in rows:
                wr.writerow(r)
    w("prefixes.tsv", ["prefix", "jp_rows", "japanese_left"] + list(C_SOURCES),
      [[p, c["jp"], c["japanese"]] + [c[k] for k in C_SOURCES] for p, c in sorted(pref.items(), key=lambda x: -x[1]["jp"])])
    w("failing.tsv", ["message_id", "source", "served_instead", "problems", "en"],
      [[f["message_id"], f["source"], b.out.get(f["message_id"], ("", "", "japanese"))[2],
        json.dumps(f["problems"], ensure_ascii=False), f["en"]] for f in b.failures])
    w("width.tsv", ["message_id", "source", "ja_px", "en_px", "ratio", "ja", "en"],
      [[m, s_, wj, we, f"{we / max(wj, 1):.2f}", src.jp_rows[m], b.out[m][1]] for m, s_, wj, we in b.width])
    w("q7.tsv", ["message_id", "served_source", "ja", "global_old_ja", "global_en"],
      [[m, b.out.get(m, ("", "", "japanese"))[2], src.jp_rows[m], src.gl_ja.get(m), src.gl_en.get(m)] for m in b.q7])
    w("token-gaps.tsv", ["message_id", "reason", "ja", "global_en"],
      [[m, why, ja, gen] for m, ja, gen, why in b.token_gaps] + [[m, why, ja, gen] for m, ja, gen, why in story_gaps])
    w("glossary-conflicts.tsv", ["ja", "en", "variants"], [[ja, en, " | ".join(v)] for ja, en, v in conflicts])
    w("glossary-warnings.tsv", ["message_id", "source", "missing_terms"],
      [[m, s_, json.dumps(x, ensure_ascii=False)] for m, s_, x in gloss_warn])
    w("overrides.tsv", ["message_id", "source", "official", "served"], b.overrides)
    w("stale.tsv", ["message_id", "source", "table_ja_sha1", "current_ja_sha1"], b.stale)
    w("e3.tsv", ["message_id", "ja", "global_en", "served"],
      [[m, src.jp_rows[m], src.gl_en[m], b.out.get(m, ("", "(failed a check)"))[1]] for m in b.e3])
    (out_dir / "summary.json").write_text(json.dumps(s, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    return s


C_SOURCES = ("official", "memory", "template", "machine", "human", "reviewed")


def cmd_report(ctx, a):
    b = build(ctx)
    s = report(ctx, b, a.out or ctx.work / "report")
    print(json.dumps(s, ensure_ascii=False, indent=1))
    print(f"lists: {a.out or ctx.work / 'report'}/", file=sys.stderr)
    return 0


# ---------------------------------------------------------------- show / set / review / stale

def cmd_show(ctx, a):
    b = build(ctx)
    src, font = ctx.src, ctx.fnt
    for mid in a.ids:
        ja = src.jp_rows.get(mid)
        print(f"== {mid}  ({C.prefix(mid)}, {b.klass.get(mid, 'new id')})")
        if ja is not None:
            print(f"ja        {ja}\n  sha1    {C.sha1(ja)}  widest {font.widest(C.unesc(ja))} px")
        if mid in src.gl_en:
            print(f"global ja {src.gl_ja.get(mid)}\nglobal en {src.gl_en.get(mid)}")
        t = b.table.get(mid)
        if t:
            print("table     " + "  ".join(f"{k}={t[k]}" for k in TABLE_COLS[1:] if t[k]))
        if mid in b.out:
            h, e, s_ = b.out[mid]
            print(f"served    [{s_}] {e}\n  widest  {font.widest(C.unesc(e))} px")
        else:
            print("served    (Japanese)")
        for f in b.failures:
            if f["message_id"] == mid:
                print(f"failing   [{f['source']}] {json.dumps(f['problems'], ensure_ascii=False)}: {f['en']}")
        for m, ja_, gen, why in b.token_gaps:
            if m == mid:
                print(f"token gap {why}")
    return 0


def today():
    return datetime.date.today().isoformat()


def cmd_set(ctx, a):
    src = ctx.src
    table = ctx.table()
    ja = src.jp_rows.get(a.id)
    text = a.text.replace("\r\n", "\n").replace("\n", "\\n")
    g = glossary_dict(glossary_rows(ctx))
    e, probs, _ = finish(ctx, g, "human", text, ja or "")
    if probs and not a.force:
        print(f"{a.id}: {json.dumps(probs, ensure_ascii=False)} (fix the text or pass --force)", file=sys.stderr)
        return 1
    table[a.id] = {"message_id": a.id, "ja_sha1": C.sha1(ja) if ja is not None else "", "en": text,
                   "source": "human", "engine": "", "date": a.date or today(), "editor": a.by, "note": a.note or ""}
    ctx.write_table(table)
    print(f"{a.id}: human row by {a.by}" + (f" (problems: {json.dumps(probs, ensure_ascii=False)})" if probs else ""))
    rebuild(ctx, a)
    return 0


def cmd_review(ctx, a):
    table = ctx.table()
    rc = 0
    for mid in a.ids:
        t = table.get(mid)
        if not t or t["source"] != "machine":
            print(f"{mid}: no machine row", file=sys.stderr)
            rc = 1
            continue
        t.update(source="reviewed", editor=a.by, date=a.date or today())
        print(f"{mid}: reviewed by {a.by}")
    ctx.write_table(table)
    rebuild(ctx, a)
    return rc


def cmd_stale(ctx, a):
    src = ctx.src
    n = 0
    for mid, t in sorted(ctx.table().items()):
        ja = src.jp_rows.get(mid)
        cur = C.sha1(ja) if ja is not None else ""
        if t["ja_sha1"] != cur or (ja is None and t["source"] not in HUMAN):
            n += 1
            print(f"{mid}\t{t['source']}\ttable {t['ja_sha1'] or '-'}\tnow {cur or '(not in the JP master)'}")
    print(f"{n} stale rows", file=sys.stderr)
    return 1 if n and a.fail else 0


# ---------------------------------------------------------------- PO and CSV round trips

def export_rows(ctx, b):
    """(mid, ja (master encoding) or "", served en, source) of every row to edit: JP rows with kana
    or kanji or with English, then the new message_ids."""
    src = ctx.src
    for mid in sorted(src.jp_rows):
        ja = src.jp_rows[mid] or ""
        if mid in b.out or C.has_kana(ja):
            o = b.out.get(mid)
            yield mid, ja, o[1] if o else "", o[2] if o else "japanese"
    for mid in sorted(set(b.out) - set(src.jp_rows)):
        yield mid, "", b.out[mid][1], b.out[mid][2]


def cmd_export_po(ctx, a):
    import polib  # only the PO round trip needs it
    b = build(ctx)
    src = ctx.src
    out = pathlib.Path(a.out or ctx.work / "po")
    out.mkdir(parents=True, exist_ok=True)
    files = {}
    for mid, ja, en, source in export_rows(ctx, b):
        p = C.prefix(mid)
        if p not in files:
            files[p] = polib.POFile(wrapwidth=0)
            files[p].metadata = {"Project-Id-Version": "soa-english", "Language": "en",
                                 "Content-Type": "text/plain; charset=UTF-8"}
        t = b.table.get(mid, {})
        comment = f"source: {source}" + (f"; engine: {t['engine']}" if t.get("engine") else "") + \
                  (f"; editor: {t['editor']}" if t.get("editor") else "")
        gl = src.gl_en.get(mid)
        extracted = f"Global: {gl}" if gl and gl != C.esc(C.unesc(en)) and not C.has_kana(gl) else ""
        files[p].append(polib.POEntry(msgctxt=mid, msgid=C.unesc(ja) or mid, msgstr=C.unesc(en),
                                      flags=["fuzzy"] if source == "machine" else [],
                                      tcomment=comment, comment=extracted))
    for p, po in sorted(files.items()):
        po.save(str(out / f"{p}.po"))
    print(f"{len(files)} .po files -> {out}")
    return 0


def apply_edits(ctx, a, edits):
    """edits: [(mid, ja as the editor saw it (real newlines) or None, english (real newlines), fuzzy)].
    A changed English becomes a human row; an unchanged machine row no longer fuzzy becomes reviewed."""
    b = build(ctx)
    src = ctx.src
    table = ctx.table()
    n = collections.Counter()
    for mid, ja_seen, en, fuzzy in edits:
        ja = src.jp_rows.get(mid)
        if ja is not None and ja_seen is not None and ja_seen != C.unesc(ja):
            n["stale (the Japanese changed)"] += 1
            continue
        if not en:
            continue
        en = C.esc(en.replace("\r\n", "\n"))
        cur = b.out.get(mid)
        if cur and cur[1] == en:
            if cur[2] == "machine" and not fuzzy:
                table[mid].update(source="reviewed", editor=a.by, date=today())
                n["reviewed"] += 1
            continue
        if ja is None and mid not in b.out:
            n["unknown id"] += 1
            continue
        table[mid] = {"message_id": mid, "ja_sha1": C.sha1(ja) if ja is not None else "", "en": en,
                      "source": "human", "engine": "", "date": today(), "editor": a.by, "note": ""}
        n["human"] += 1
    ctx.write_table(table)
    print(dict(n))
    rebuild(ctx, a)
    return 0


def cmd_import_po(ctx, a):
    import polib
    edits = []
    for f in a.files:
        for e in polib.pofile(f):
            if e.msgctxt:
                ja = None if e.msgid == e.msgctxt else e.msgid
                edits.append((e.msgctxt, ja, e.msgstr, "fuzzy" in e.flags))
    return apply_edits(ctx, a, edits)


CSV_COLS = ["message_id", "source", "ja", "global_en", "en", "ja_px", "en_px", "problems"]


def cmd_export_csv(ctx, a):
    b = build(ctx)
    src, font = ctx.src, ctx.fnt
    fails = collections.defaultdict(list)
    for f in b.failures:
        fails[f["message_id"]].append(f"{f['source']}: {json.dumps(f['problems'], ensure_ascii=False)}")
    out = pathlib.Path(a.out or ctx.work / "english.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(CSV_COLS)
        for mid, ja, en, source in export_rows(ctx, b):
            gl = src.gl_en.get(mid, "")
            wr.writerow([mid, source, ja, gl if not C.has_kana(gl) else "", en,
                         font.widest(C.unesc(ja)), font.widest(C.unesc(en)) if en else "", "; ".join(fails[mid])])
    print(f"-> {out}")
    return 0


def cmd_import_csv(ctx, a):
    edits = []
    with open(a.file, encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            edits.append((r["message_id"], C.unesc(r["ja"]) if r.get("ja") else None, C.unesc(r.get("en") or ""), False))
    return apply_edits(ctx, a, edits)


# ---------------------------------------------------------------- import-mt

def engine_name(r):
    return f"{r['model']}/{r['quant']}/{r['prompt']}/llama.cpp-{r['llama_build']}/t{r['temperature']}"


def cmd_import_mt(ctx, a):
    b = build(ctx)
    src, font = ctx.src, ctx.fnt
    table = ctx.table()
    rej_path = ctx.work / "mt-rejected.tsv"
    rejected = {r["message_id"]: r for r in read_tsv(rej_path, REJECT_COLS)}
    n = collections.Counter()
    with open(a.checkpoint, encoding="utf-8") as f:
        lines = [json.loads(x) for x in f if x.strip()]
    for r in lines:
        engine = engine_name(r)
        for mid in r["ids"]:
            ja = src.jp_rows.get(mid)
            if ja is None:
                n["not in the JP master"] += 1
                continue
            h = C.sha1(ja)
            if r["ja_sha1"] != h:
                n["hash mismatch"] += 1
                continue
            t = table.get(mid)
            if t and t["source"] in HUMAN:
                n["kept: human/reviewed"] += 1
                continue
            served = b.out.get(mid)
            if served and served[2] in DERIVED + HUMAN:
                n["kept: covered by " + served[2]] += 1
                continue
            if t and t["source"] == "machine":
                if not a.replace:
                    n["kept: machine row exists"] += 1
                    continue
                if t["ja_sha1"] == h and t["engine"] == engine:
                    n["kept: same hash, engine and prompt"] += 1
                    continue
            jn = C.unesc(ja)
            row = {"ja": ja, "budget": font.widest(jn), "multiline": "\n" in jn}
            en, probs = C.post_one(row, r["mt"], font, b.glossary)
            probs.pop("width", None)  # single-line width is reported, not failed (the client wraps, E10)
            if not probs:
                _, probs, _ = finish(ctx, b.glossary, "machine", C.esc(en), ja)
            if probs:
                rejected[mid] = {"message_id": mid, "ja_sha1": h, "engine": engine, "date": r.get("date", ""),
                                 "en": C.esc(en), "problems": json.dumps(probs, ensure_ascii=False)}
                n["rejected"] += 1
                continue
            rejected.pop(mid, None)
            table[mid] = {"message_id": mid, "ja_sha1": h, "en": C.esc(en), "source": "machine",
                          "engine": engine, "date": r.get("date", ""), "editor": "", "note": ""}
            n["imported"] += 1
    ctx.write_table(table)
    if rejected or rej_path.exists():
        rej_path.parent.mkdir(parents=True, exist_ok=True)
        rej_path.write_text(tsv_text(REJECT_COLS, [rejected[m] for m in sorted(rejected)]), encoding="utf-8")
    print(json.dumps(dict(sorted(n.items())), ensure_ascii=False))
    if n["rejected"]:
        print(f"rejected rows: {rej_path}", file=sys.stderr)
    rebuild(ctx, a)
    return 0


# ---------------------------------------------------------------- main

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", default=str(DATA))
    ap.add_argument("--master", default=str(C.MASTER_DB))
    ap.add_argument("--gl", default=str(C.GLOBAL_DB))
    ap.add_argument("--scenario", default=str(C.SCENARIO_DIR))
    ap.add_argument("--font", default=None, help="font.fpk, an .apk, or a glyphs .pkl (default: the committed APK)")
    ap.add_argument("--work", default=str(WORK))
    ap.add_argument("--no-build", action="store_true", help="edits: don't rebuild master-en.tsv afterwards")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("build")
    p.add_argument("--check", action="store_true")
    p = sub.add_parser("report")
    p.add_argument("--out")
    p = sub.add_parser("show")
    p.add_argument("ids", nargs="+")
    p = sub.add_parser("set")
    p.add_argument("id")
    p.add_argument("text")
    p.add_argument("--by", required=True)
    p.add_argument("--note")
    p.add_argument("--date")
    p.add_argument("--force", action="store_true")
    p = sub.add_parser("review")
    p.add_argument("ids", nargs="+")
    p.add_argument("--by", required=True)
    p.add_argument("--date")
    p = sub.add_parser("stale")
    p.add_argument("--fail", action="store_true", help="exit 1 when any row is stale")
    p = sub.add_parser("export-po")
    p.add_argument("--out")
    p = sub.add_parser("import-po")
    p.add_argument("files", nargs="+")
    p.add_argument("--by", required=True)
    p = sub.add_parser("export-csv")
    p.add_argument("--out")
    p = sub.add_parser("import-csv")
    p.add_argument("file")
    p.add_argument("--by", required=True)
    p = sub.add_parser("import-mt")
    p.add_argument("checkpoint")
    p.add_argument("--replace", action="store_true",
                   help="replace machine rows whose hash, engine or prompt changed")
    a = ap.parse_args(argv)
    ctx = Ctx(a.data, a.master, a.gl, a.scenario, a.font, a.work)
    cmds = {"build": cmd_build, "report": cmd_report, "show": cmd_show, "set": cmd_set, "review": cmd_review,
            "stale": cmd_stale, "export-po": cmd_export_po, "import-po": cmd_import_po,
            "export-csv": cmd_export_csv, "import-csv": cmd_import_csv, "import-mt": cmd_import_mt}
    return cmds[a.cmd](ctx, a)


if __name__ == "__main__":
    sys.exit(main())
