"""Generate port/src/native/params/gen/parameter_tables.inc from libSOA.so.

The master-parameter code is one C++ template instantiated per record type, plus ~175 trivial
CParameterManager accessors. This lists every instantiation the native port replaces, so the
C++ side can register one handler per instance:

  PM_ACCESSOR2(sym, off1, off2)   ldr x8,[x0,#off1]; ldr x0,[x8,#off2]; ret
  PM_ACCESSOR1(sym, off)          ldr x0,[x0,#off]; ret
  SIMPLE_FROM_HASH(i, sym, vtable)      CMasterParameterBaseSqlite_Simple<T>::pParameterFromHash(u32)
  CATEGORY_FROM_HASH(i, sym, vtable)    CMasterParameterBaseSqlite_Category<T>::pParameterFromHash(u32)
  SIMPLE_BY_QUERY(i, sym, vtable)            CMasterParameterBaseSqlite_Simple<T>::ParameterByQuery(const char*, QueryParam*, u32)
  SIMPLE_CACHE_KEY(sym)                 CMasterParameterBaseSqlite_Simple<T>::MakeCacheKey(const char*, QueryParam*, u32)
  SIMPLE_CLEAR_CACHE / SIMPLE_INITIALIZE(_THUNK) / SIMPLE_DESERIALIZE(_THUNK) / SIMPLE_RELEASE(sym)
  SIMPLE_INSERT_QUERY_CACHE(sym)        InsertCustomizeCache (used by the tests to build maps)
  CATEGORY_BY_NAME(i, sym, size, emplace_vtable, ctor, assign, from_hash_u32, pParameter)
                                        Category<T>::pParameterFromHash(const char*, u32) / pParameter
  PROP_NAME_HASH / PROP_COMPARE_HASH / PROP_COMPARE_NAME(sym)   CParameterPropertyBase<N>::NameHash / CompareName
  PROP_CRYPT_STRING(N, sym)             CParameterPropertyBase<N>::CryptString<string>(string&, const string&)
  PROP_VALUE_DESERIALIZE(t, N, sym)     CParameterPropertyValue<t, N, CPropertyConverter>::Deserialize(const AMap*)
                                        (t = the mangled type letter: j u32, f float, b bool, m u64, i int, h u8)
  PROP_STRING_DESERIALIZE(N, sym)       CParameterPropertyString<string, N>::Deserialize(const AMap*)

Usage: .venv/bin/python tools/gen_parameter_tables.py > port/src/native/params/gen/parameter_tables.inc
"""
import re

from capstone import CS_ARCH_ARM64, CS_MODE_ARM, Cs
import genlib  # (before a2c / elfinfo: the default lib is 3.7.0's; tools/genlib.py)
from elfinfo import lib

L = lib()
md = Cs(CS_ARCH_ARM64, CS_MODE_ARM)
dyn = {s.name: s["st_value"] for s in L.elf.get_section_by_name(".dynsym").iter_symbols() if s.name and s["st_value"]}


def insns(addr, n):
    return [(i.mnemonic, i.op_str) for i in md.disasm(L.read(addr, 4 * n), addr)]


out = ["// Generated by tools/gen_parameter_tables.py from libSOA.so -- do not edit.",
       "// " + genlib.stamp(),
       "// Each section is only expanded when the includer defines its macro.", ""]


def section(macro, lines):
    out.append("#ifdef " + macro)
    out.extend(lines)
    out.append("#endif")
    out.append("")


acc1 = re.compile(r"ldr x0, \[x0, #(0x[0-9a-f]+)\]$")
acc2a = re.compile(r"ldr x8, \[x0, #(0x[0-9a-f]+)\]$")
acc2b = re.compile(r"ldr x0, \[x8, #(0x[0-9a-f]+)\]$")
a1, a2 = [], []
for name in sorted(n for n in dyn if n.startswith("_ZNK17CParameterManager")):
    ins = insns(dyn[name], 3)
    ops = ["%s %s" % i for i in ins]
    if len(ops) >= 2 and acc1.match(ops[0]) and ops[1] == "ret ":
        a1.append('PM_ACCESSOR1("%s", %s)' % (name, acc1.match(ops[0]).group(1)))
    elif len(ops) >= 3 and acc2a.match(ops[0]) and acc2b.match(ops[1]) and ops[2] == "ret ":
        a2.append('PM_ACCESSOR2("%s", %s, %s)' % (name, acc2a.match(ops[0]).group(1), acc2b.match(ops[1]).group(1)))
section("PM_ACCESSOR1", a1)
section("PM_ACCESSOR2", a2)


def instances(kind, method):
    pat = re.compile(r"^_ZNK?(33CMasterParameterBaseSqlite_Simple|35CMasterParameterBaseSqlite_Category)(I.*E)" + method + "$")
    r = []
    for name in sorted(dyn):
        m = pat.match(name)
        if m and m.group(1).endswith(kind):
            vt = "_ZTV" + m.group(1) + m.group(2)
            r.append((name, vt if vt in dyn else None))
    return r


section("SIMPLE_FROM_HASH", ['SIMPLE_FROM_HASH(%d, "%s", "%s")' % (i, n, vt or "")
                            for i, (n, vt) in enumerate(instances("Simple", "18pParameterFromHashEj"))])
section("CATEGORY_FROM_HASH", ['CATEGORY_FROM_HASH(%d, "%s", "%s")' % (i, n, vt or "")
                              for i, (n, vt) in enumerate(instances("Category", "18pParameterFromHashEj"))])
section("SIMPLE_BY_QUERY", ['SIMPLE_BY_QUERY(%d, "%s", "%s")' % (i, n, vt or "")
                           for i, (n, vt) in enumerate(instances("Simple", "16ParameterByQueryEPKcPN4Aska5Yayoi10QueryParamEj"))])
section("SIMPLE_CACHE_KEY", ['SIMPLE_CACHE_KEY("%s")' % n
                            for n, _ in instances("Simple", "12MakeCacheKeyEPKcPN4Aska5Yayoi10QueryParamEj")])

def prop(method):
    pat = re.compile(r"^_ZNK?22CParameterPropertyBaseILj(\d+)EE" + method + "$")
    return sorted(((int(m.group(1)), n) for n in dyn for m in [pat.match(n)] if m))


section("SIMPLE_CLEAR_CACHE", ['SIMPLE_CLEAR_CACHE("%s")' % n for n, _ in instances("Simple", "10ClearCacheEv")])
# (Initialize is the same for the Category<T> tables)
section("SIMPLE_INITIALIZE", ['SIMPLE_INITIALIZE("%s")' % n for n, _ in instances("Simple", "10InitializeEv") + instances("Category", "10InitializeEv")])
section("SIMPLE_INITIALIZE_THUNK", ['SIMPLE_INITIALIZE_THUNK("%s")' % n for n in sorted(dyn) if re.match(
    r"^_ZThn16_N3[35]CMasterParameterBaseSqlite_(Simple|Category)I.*E10InitializeEv$", n)])
section("SIMPLE_DESERIALIZE", ['SIMPLE_DESERIALIZE("%s")' % n for n, _ in instances("Simple", "11DeserializeEPKN4Aska4ASON6AValue4AMapE")])
section("SIMPLE_DESERIALIZE_THUNK", ['SIMPLE_DESERIALIZE_THUNK("%s")' % n for n in sorted(dyn) if re.match(
    r"^_ZThn16_N33CMasterParameterBaseSqlite_SimpleI.*E11DeserializeEPKN4Aska4ASON6AValue4AMapE$", n)])
section("SIMPLE_RELEASE", ['SIMPLE_RELEASE("%s")' % n for n, _ in instances("Simple", "16ReleaseParameterEPKc")])
section("SIMPLE_INSERT_QUERY_CACHE", ['SIMPLE_INSERT_QUERY_CACHE("%s")' % n for n, _ in instances(
    "Simple", "20InsertCustomizeCacheEjRKNSt6__ndk110shared_ptrIS0_EE")])


def category_by_name():
    """Category<T>::pParameterFromHash(const char*, u32): per instance, the shared_ptr_emplace
    allocation size, its vtable, and the element's constructor and operator= (read from the code)."""
    md.detail = True
    rows = []
    for i, (name, _) in enumerate(instances("Category", "18pParameterFromHashEPKcj")):
        a = dyn[name]
        size = vt = ctor = assign = None
        prev = None
        page = 0
        for ins in md.disasm(L.read(a, 0x200), a):
            if ins.mnemonic == "adrp":
                page = ins.operands[1].imm
            if ins.mnemonic == "ldr" and ins.op_str.startswith("x8, [x8") and page:
                vt = L.got2name.get(page + ins.operands[1].mem.disp)
            if ins.mnemonic == "bl":
                t = ins.operands[0].imm
                tn = L.plt.get(t) or L.by_addr.get(t)
                if tn == "_Znwm" and prev and prev.mnemonic == "mov":
                    size = prev.operands[1].imm
                elif tn and tn.endswith("C2Ev") and size:
                    ctor = tn
                elif tn and "aSERKS_" in tn and ctor:
                    assign = tn
                    break
            prev = ins
        if None in (size, vt, ctor, assign):
            continue  # a different code shape (e.g. through allocate_shared): not replaced
        u32_sym = name.replace("18pParameterFromHashEPKcj", "18pParameterFromHashEj")
        param_sym = name.replace("18pParameterFromHashEPKcj", "10pParameterEPKcS3_")
        rows.append('CATEGORY_BY_NAME(%d, "%s", %#x, "%s", "%s", "%s", "%s", "%s")' % (
            i, name, size, vt, ctor, assign, u32_sym, param_sym if param_sym in dyn else ""))
    return rows


section("CATEGORY_BY_NAME", category_by_name())
section("PROP_NAME_HASH", ['PROP_NAME_HASH("%s")' % n for _, n in prop("8NameHashEv")])
section("PROP_COMPARE_HASH", ['PROP_COMPARE_HASH("%s")' % n for _, n in prop("11CompareNameEj")])
section("PROP_COMPARE_NAME", ['PROP_COMPARE_NAME("%s")' % n for _, n in prop("11CompareNameEPKc")])
section("PROP_CRYPT_STRING", ['PROP_CRYPT_STRING(%d, "%s")' % (k, n) for k, n in prop(
    "11CryptStringINSt6__ndk112basic_stringIcNS2_11char_traitsIcEEN9Framework13CSTLAllocatorIcNS6_22CSTLStringAllocatorInfEEEEEEEvRT_RKSB_")])

vals, strs = [], []
for n in sorted(dyn):
    m = re.match(r"^_ZN23CParameterPropertyValueI([a-z])Lj(\d+)E18CPropertyConverterE11DeserializeEPKN4Aska4ASON6AValue4AMapE$", n)
    if m and m.group(1) in "jfbmih":
        vals.append((m.group(1), int(m.group(2)), n))
    m = re.match(r"^_ZN24CParameterPropertyStringINSt6__ndk112basic_stringIcNS0_11char_traitsIcEEN9Framework13CSTLAllocatorIcNS4_"
                 r"22CSTLStringAllocatorInfEEEEELj(\d+)EE11DeserializeEPKN4Aska4ASON6AValue4AMapE$", n)
    if m:
        strs.append((int(m.group(1)), n))
section("PROP_VALUE_DESERIALIZE", ['PROP_VALUE_DESERIALIZE(%s, %d, "%s")' % v for v in sorted(vals, key=lambda v: (v[0], v[1]))])
section("PROP_STRING_DESERIALIZE", ['PROP_STRING_DESERIALIZE(%d, "%s")' % v for v in sorted(strs)])
print("\n".join(out))
