#!/usr/bin/env -S sh -c 'exec "${0%/*}/py" "$0" "$@"'
"""Generates port/src/native/ui/cocos/gen/cocos_guireader_a2c.cpp: the layout reader (CCocosGuiReader::CreateTree
and its Read_* family) and CCocosTimelineAnimation Play / GetHandle / MakeKeyFrameLinks, transcribed
from the ARM64 by a2c.py (CALL_FALLBACK: node constructors, factories, AddKeyFrame, ASON and string
calls go to the guest through objmgr's a2c_call, i.e. to native replacements where they exist).
Usage: tools/gen_guireader_a2c.py port/src/native/ui/cocos/gen/cocos_guireader_a2c.cpp"""
import importlib.util
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib  # noqa: E402 (before a2c / elfinfo: the default lib is 3.7.0's; tools/genlib.py)
_spec = importlib.util.spec_from_file_location('a2c', os.path.join(os.path.dirname(os.path.abspath(__file__)), 'a2c.py'))
a2c = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(a2c)
a2c.EXCLUSIVE = True

GR = '_ZN9Framework5Cocos15CCocosGuiReader'
NODE_ARGS = 'EPNS0_10CCocosNodeERKN4Aska4ASON6AValueE'
TL = '_ZN9Framework5Cocos23CCocosTimelineAnimation'
# (symbol, body name). The one-instruction Read_* stubs (GameMap, SimpleAudio, TextBMFont,
# ArmatureNode: `ret`) stay guest.
SPEC = [
    (GR + '10CreateTreeERKNS_20CResourceElement_CsfERNS0_10CCocosNodeERNS0_19CCocosObjectFactoryE', 'gr_create_tree'),
    (GR + '10Read_Scene' + NODE_ARGS, 'gr_scene'),
    (GR + '12Read_Content' + NODE_ARGS, 'gr_content'),
    (GR + '20Read_GameProjectData' + NODE_ARGS, 'gr_game_project_data'),
    (GR + '15Read_ObjectData' + NODE_ARGS, 'gr_object_data'),
    (GR + '14Read_AnimationERKN4Aska4ASON6AValueE', 'gr_animation'),
    (GR + '18Read_AnimationListERKN4Aska4ASON6AValueE', 'gr_animation_list'),
    (GR + '14Read_TimelinesERKN4Aska4ASON6AValueE', 'gr_timelines'),
    (GR + '17Read_TimelineDataERKN4Aska4ASON6AValueE', 'gr_timeline_data'),
    (GR + '11Read_FramesEPKciRKN4Aska4ASON6AValueE', 'gr_frames'),
    (GR + '22Read_AnimationInfoDataERKN4Aska4ASON6AValueE', 'gr_animation_info_data'),
    (GR + '25Read_SingleNodeObjectData' + NODE_ARGS, 'gr_single_node'),
    (GR + '13Read_Children' + NODE_ARGS, 'gr_children'),
    (GR + '23Read_ParticleObjectData' + NODE_ARGS, 'gr_particle'),
    (GR + '21Read_SpriteObjectData' + NODE_ARGS, 'gr_sprite'),
    (GR + '21Read_ButtonObjectData' + NODE_ARGS, 'gr_button'),
    (GR + '23Read_CheckBoxObjectData' + NODE_ARGS, 'gr_check_box'),
    (GR + '24Read_ImageViewObjectData' + NODE_ARGS, 'gr_image_view'),
    (GR + '19Read_TextObjectData' + NODE_ARGS, 'gr_text'),
    (GR + '24Read_AtlasTextObjectData' + NODE_ARGS, 'gr_atlas_text'),
    (GR + '25Read_LoadingBarObjectData' + NODE_ARGS, 'gr_loading_bar'),
    (GR + '21Read_SliderObjectData' + NODE_ARGS, 'gr_slider'),
    (GR + '24Read_TextFieldObjectData' + NODE_ARGS, 'gr_text_field'),
    (GR + '20Read_PanelObjectData' + NODE_ARGS, 'gr_panel'),
    (GR + '23Read_ListViewObjectData' + NODE_ARGS, 'gr_list_view'),
    (GR + '23Read_PageViewObjectData' + NODE_ARGS, 'gr_page_view'),
    (GR + '25Read_ScrollViewObjectData' + NODE_ARGS, 'gr_scroll_view'),
    ('_ZN9Framework5Cocos23CCocosTimelineAnimation4PlayERKNSt6__ndk112basic_stringIcNS2_11char_traitsIcEENS_13CSTLAllocatorIcNS_22CSTLStringAllocatorInfEEEEEjjbNS2_8functionIFvvEEE', 'tl_play'),
    ('_ZNK9Framework5Cocos23CCocosTimelineAnimation9GetHandleERKNSt6__ndk112basic_stringIcNS2_11char_traitsIcEENS_13CSTLAllocatorIcNS_22CSTLStringAllocatorInfEEEEE', 'tl_get_handle'),
    (TL + '17MakeKeyFrameLinksEv', 'tl_make_key_frame_links'),
]


def call_fallback(kind, target, reg):
    fn = f'LIB + {target:#x}' if target is not None else reg
    return f'GR_CALL({fn});'


a2c.CALL_FALLBACK = call_fallback
for sym, name in SPEC:
    a2c.EXTRA_CALLS[sym] = f'A2C_NATIVE(b_{name});'
a2c.CALLS['memset'] = 'std::memset((void*)X(0), (int)W(1), (size_t)X(2));'
a2c.CALLS['memcpy'] = 'std::memcpy((void*)X(0), (const void*)X(1), (size_t)X(2));'
a2c.CALLS['memmove'] = 'std::memmove((void*)X(0), (const void*)X(1), (size_t)X(2));'
a2c.CALLS['strlen'] = 'X(0) = std::strlen((const char*)X(0));'

OUT = sys.argv[1]
out = ['// GENERATED by tools/gen_guireader_a2c.py from libSOA.so (a2c.py: CALL_FALLBACK + EXCLUSIVE) -- do not edit.',
       '// ' + genlib.stamp(),
       '// The layout reader (CCocosGuiReader) and CCocosTimelineAnimation Play / GetHandle /',
       '// MakeKeyFrameLinks, transcribed instruction by instruction (see cocos_guireader.cpp for how',
       '// they are hooked and tested).',
       '#include <cstring>',
       '',
       '#include "native/engine/math/aska_math_a2c.h"',
       '#include "native/engine/objmgr_a2c.h"',
       '',
       'namespace soa::objmgr::a2c_body {',
       'using namespace ::soa::aska::a2c;',
       '// Like A2C_CALL, but the result comes back in x0-x1 and v0-v3 (CResourceElement_Csf::SceneImage',
       '// returns a {data, size} pair in x0 / x1).',
       'void gr_call(A64& r, u64 fn);',
       '#define GR_CALL(fn) ::soa::objmgr::a2c_body::gr_call(r, (fn))',
       '']
for sym, name in SPEC:
    out.append(f'void b_{name}(A64& r);')
out.append('')
for sym, name in SPEC:
    body = a2c.translate(sym, name)
    if '#error' in body:
        sys.exit(f'{sym}: untranslated instructions')
    out.append(f'void b_{name}(A64& r) {{')
    out.append('    u64 jt_ = 0, ex_a_ = 0, ex_v_ = 0;')
    out.append('    (void)jt_, (void)ex_a_, (void)ex_v_;')
    out.append(body.rstrip())
    out.append('}')
    out.append('')
out.append('}  // namespace soa::objmgr::a2c_body')
open(OUT, 'w').write('\n'.join(out) + '\n')
