#!/usr/bin/env python3
"""Generates port/src/native/api/gen/api_notify_a2c.cpp: CApiNotify functions transcribed by a2c.py.

CApiNotify::DeserializeToInfo (7.6 KB) is almost entirely inlined constructors / destructors of
the ~60 per-response result containers it resets (maps, vectors of InfoBase-derived elements, the
mission drop infos) before handing the body to ASON and CParameterManager::Deserialize. It is
transcribed instruction by instruction instead of hand-written. Outgoing calls are guest calls
(models_gcall / models_icall), so natively replaced callees (CParameterManager::Deserialize, the
tree helpers, ...) still run natively through their hooks.

Usage: gen_apinotify_a2c.py <out.cpp>
"""
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib  # noqa: E402 (before a2c / elfinfo: the default lib is 3.7.0's; tools/genlib.py)
_spec = importlib.util.spec_from_file_location('a2c', os.path.join(HERE, 'a2c.py'))
a2c = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(a2c)
L = a2c.L
OUT = sys.argv[1]

FUNCS = [
    '_ZN10CApiNotify17DeserializeToInfoEPaRj',
]

dyn = a2c.syms
HOST = {
    'memset': 'memset((void*)X(0), (int)W(1), X(2));',
    'memcpy': 'memcpy((void*)X(0), (const void*)X(1), X(2));',
    'memmove': 'memmove((void*)X(0), (const void*)X(1), X(2));',
}
calls = {}


def fallback(kind, t, reg):
    if kind in ('blr', 'br'):
        return f'models_icall(r, {reg});'
    n = L.name(t)
    if n.startswith('PLT:') and n[4:] in HOST:
        return HOST[n[4:]]
    calls[t] = n
    return f'models_gcall(r, LIB + 0x{t:x}); /* {a2c.dem(n.replace("PLT:", ""))[:80]} */'


a2c.CALL_FALLBACK = fallback
a2c.EXCLUSIVE = True
a2c.NAN_EXACT = True
a2c.EXTRA_CALLS.clear()
for k in ('__cxa_guard_acquire', '__cxa_guard_release'):
    a2c.CALLS.pop(k, None)

out = ['''// GENERATED by tools/gen_apinotify_a2c.py from libSOA.so's ARM64 code: do not edit by hand; regenerate.
// ''' + genlib.stamp() + '''
//
// CApiNotify::DeserializeToInfo transcribed instruction by instruction by tools/a2c.py (the reset
// of every per-response result container, inlined constructors / destructors included, then
// ASON + CParameterManager::Deserialize and the host-player refresh). Calls are guest calls
// (models_gcall / models_icall). Registration and tests: api_notify.cpp, api_notify_test.cpp.
#pragma GCC optimize("fp-contract=off")
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wuninitialized"
#include <cstdlib>
#include <cstring>

#include "core/cpu.h"
#include "native/engine/math/aska_math.h"
#include "native/models/models.h"

namespace soa::native::apinotify {
using namespace ::soa::aska;
using namespace ::soa::aska::a2c;
using namespace ::soa::models;
using a2c::u64;
using a2c::u32;
''']
bad = []
bodies = []
table = []
for n in FUNCS:
    a, s = dyn[n]
    body = a2c.translate(n, f'f_{a:x}')
    if '#error' in body:
        bad.append((n, re.findall(r'#error "a2c: ([^"]*)"', body)[:3]))
    bodies.append(f'// {a2c.dem(n)}')
    bodies.append(f'void a2c_{a:x}(A64& r) {{')
    bodies.append('    u64 jt_ = 0, ex_a_ = 0, ex_v_ = 0;')
    bodies.append('    (void)jt_; (void)ex_a_; (void)ex_v_;')
    bodies.append(body.rstrip())
    bodies.append('}')
    table.append((n, a))
out += bodies
out.append('')
for n, a in table:
    out.append(f'// {n}')
    out.append(f'void a2c_deserialize_to_info(A64& r) {{ a2c_{a:x}(r); }}')
out.append('}  // namespace soa::native::apinotify')
open(OUT, 'w').write('\n'.join(out) + '\n')
for n, e in bad:
    print(f'UNSUPPORTED {n}: {e}', file=sys.stderr)
print(f'{len(table)} bodies, {len(calls)} call targets, {len(bad)} unsupported', file=sys.stderr)
