#!/usr/bin/env python3
"""Generates server/src/core/errors.h: the client error codes the local server refuses with.

    tools/gen_error_codes.py [--master DB] [--check]

The client shows master_text error_message_text_<code> (lang ja) for the code a refused request
reports (ext::refuse, the core's refusal path). This reads those texts from the 3.7.0 master
(data/basmaster-3.7.0.sqlite3 by default; 137 codes) and writes one `enum class ErrorCode : u32`
with a hand-chosen name for each code the server uses (NAMES below, with the note on why that
code) and the client's text as the comment; the codes the server doesn't use are listed in a
comment table. --check exits 1 when the committed header differs from what it would write.
server/PLAN-readability.md 2.4.
"""
import argparse
import os
import sqlite3
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "server/src/core/errors.h")

# code -> (name, note). The note is the source label of the choice (the code is the server's
# decision where the client has several codes with one text).
NAMES = {
    10002: ("kPlayerNotFound", "(b) the client's own dialog for SearchPlayer (api/player/home_footer.cpp)"),
    10004: ("kStaminaShort", "(a) the text; MissionStart, Sphere211MissionStart"),
    10009: ("kBirthUnknown", "(b) RequestGetAge's lambda @019587d8 opens the birth dialog"),
    10202: ("kEquipSlotsShort", "(a) the text; withdraws past item_stock (api/storage)"),
    10203: ("kEquippedItem", "(a) the text; DepositItem (api/storage)"),
    10204: ("kLockedItem", "(a) the text"),
    10206: ("kItemCountError", "(a) the text: items, tickets, vanish items short (d: the code)"),
    10208: ("kItemUnusable", "(d) the server's generic refusal"),
    10211: ("kStorageShort", "(a) the text; DepositItem (api/storage)"),
    10403: ("kInvalidOperation", "(a) the text; (d) the gacha refusals"),
    10710: ("kFolShort", "(d) which of the FOL codes (10706 / 10710 / 11001): ext.h \"refuse\""),
    11001: ("kFolShortGrowth", "(d) the FOL code of the item compose / grade-up refusals"),
    11002: ("kLevelCap", "(a) the text"),
    11006: ("kLimitReached", "(a) the text"),
    17001: ("kExchangeExpired", "(a) the text"),
    19001: ("kNoPlayer", "(b) the Login result lambda: \"no account yet\" starts the new-player flow"),
    20000: ("kCoinsShort", "(a) the text; (d) of 20000 / 20003"),
}


def texts(db):
    con = sqlite3.connect("file:%s?mode=ro" % db, uri=True)
    rows = con.execute("select message_id, text_value from master_text where message_id like 'error_message_text_%' and lang = 'ja'").fetchall()
    out = {}
    for mid, text in rows:
        try:
            out[int(mid[len("error_message_text_"):])] = (text or "").replace("\n", "\\n")
        except ValueError:
            pass
    return out


def render(t):
    missing = [c for c in NAMES if c not in t]
    if missing:
        sys.exit("gen_error_codes: no master_text for %s" % missing)
    lines = [
        "#pragma once",
        "// GENERATED by tools/gen_error_codes.py from data/basmaster-3.7.0.sqlite3 master_text; do not edit.",
        "// The client error codes the local server refuses requests with (server/PLAN-readability.md 2.4).",
        "// The client shows master_text error_message_text_<code> (lang ja), the comment of each code;",
        "// the label after it says why the server uses that code.",
        "#include \"soaserver/ext.h\"",
        "",
        "namespace soa::server {",
        "",
        "enum class ErrorCode : u32 {",
    ]
    for code in sorted(NAMES):
        name, note = NAMES[code]
        lines.append("    %s = %d,  // %s %s" % (name, code, t[code], note))
    lines += [
        "};",
        "",
        "namespace ext {",
        "// ext::refuse with a named code (soaserver/ext.h).",
        "inline std::vector<u8> refuse(Ctx& c, const char* method, const char* why, ErrorCode code) { return refuse(c, method, why, (u32)code); }",
        "}  // namespace ext",
        "",
        "// The client's other error codes (not sent by the local server):",
    ]
    for code in sorted(t):
        if code not in NAMES:
            lines.append("//   %d  %s" % (code, t[code]))
    lines += ["", "}  // namespace soa::server", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--master", default=os.path.join(REPO, "data/basmaster-3.7.0.sqlite3"))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render(texts(a.master))
    if a.check:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("gen_error_codes: %s is stale: run tools/gen_error_codes.py" % os.path.relpath(OUT, REPO))
            return 1
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s" % os.path.relpath(OUT, REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main())
