#!/usr/bin/env -S sh -c 'exec "${0%/*}/py" "$0" "$@"'
"""Generates port/src/native/arena/gen/arena_a2c.cpp: the arena / effect / collision layer transcribed by a2c.py.

CArena (the battle / home / gacha scene driver), CArenaEffectManager / CArenaEffectModel,
Framework::CEffectManager (+ CPiece) / Framework::CEffectModel and the game-namespace Collision::*
classes, instruction by instruction. The functions listed are the ones that executed in the
2026-09-29 restore-run profile (battles, home, gacha, deep space). Small hot functions are also
hand-written (arena.cpp); those symbols are registered from there instead, and their
transcriptions stay as test references.

Every outgoing call goes through arena_gcall() / arena_icall() (arena.h): calls to other
transcribed functions of this table run their bodies directly, other calls go to the guest (or
the host function of another native), and the live check (soa --live-check arena) records and replays
them (arena_rt.cpp).

Usage: .venv/bin/python tools/gen_arena_a2c.py port/src/native/arena/gen/arena_a2c.cpp
"""
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib  # noqa: E402 (before a2c / elfinfo: the default lib is 3.7.0's; tools/genlib.py)
_spec = importlib.util.spec_from_file_location('a2c', os.path.join(HERE, 'a2c.py'))
a2c = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(a2c)
L = a2c.L
OUT = sys.argv[1]

# Bytes of the object at x0 the live check snapshots, by class (the largest field offset the
# class's functions touch, rounded up); 0 for functions whose x0 isn't an object of the family.
OBJ = [
    ('CArenaEffectManager::', 0xb0),
    ('CArenaEffectModel::', 0x2c0),
    ('CArena::IGetHeight::', 0),
    ('CArena::', 0x1c0),
    ('Framework::CEffectManager::CPiece::', 0x60),
    ('Framework::CEffectManager::', 0x38),
    ('Framework::CEffectModel::', 0x1e8),
    ('Collision::CCollisionAlgorithm::', 0x198),
    ('Collision::CCollisionContainer::', 0x38),
    ('Collision::CCollisionField::', 0x48),
    ('Collision::CCollisionShapeAcf::', 0x38),
    ('Collision::CCollisionShapeBox::', 0xd0),
    ('Collision::CCollisionShapeCapsule::', 0xa0),
    ('Collision::CCollisionShapeBase::', 0x10),
    ('Collision::CollisionShapeGroup::', 0x28),
    ('Collision::Math::', 0),
]

# Executed functions of the family (profile coverage), mangled.
FUNCS = [ln.strip() for ln in open(os.path.join(HERE, 'arena_funcs.txt')) if ln.strip() and not ln.startswith('#')]

dyn = a2c.syms
# memset / memcpy / memmove run on the host (arena_memop, arena.h: 1 / 2 / 3); the live check
# records them like calls.
HOST = {'memset': 1, 'memcpy': 2, 'memmove': 3}
calls = {}


def fallback(kind, t, reg):
    if kind in ('blr', 'br'):
        return f'arena_icall(r, {reg});'
    n = L.name(t)
    if n.startswith('PLT:') and n[4:] in HOST:
        return f'arena_memop(r, LIB + 0x{t:x}, {HOST[n[4:]]});'

    calls[t] = n
    return f'arena_gcall(r, LIB + 0x{t:x}); /* {a2c.dem(n.replace("PLT:", ""))[:80]} */'


a2c.CALL_FALLBACK = fallback
a2c.EXCLUSIVE = True
a2c.NAN_EXACT = True
a2c.EXTRA_CALLS.clear()
for k in ('__cxa_guard_acquire', '__cxa_guard_release'):
    a2c.CALLS.pop(k, None)

out = ['''// GENERATED by tools/gen_arena_a2c.py from libSOA.so's ARM64 code: do not edit by hand; regenerate.
// ''' + genlib.stamp() + '''
//
// The arena / effect / collision layer (CArena, CArenaEffect*, Framework::CEffectManager /
// CEffectModel, Collision::*) transcribed instruction by instruction by tools/a2c.py. Calls go
// through arena_gcall / arena_icall (arena.h). Registration, switches and tests: arena_rt.cpp.
#pragma GCC optimize("fp-contract=off")
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wuninitialized"
#include <cstdlib>
#include <cstring>

#include "core/cpu.h"
#include "native/arena/arena.h"
#include "native/engine/math/aska_math.h"
#include "native/models/models.h"

namespace soa::arena {
using namespace ::soa::aska;
using namespace ::soa::aska::a2c;
using namespace ::soa::models;
using a2c::u64;
using a2c::u32;

// Stores (for the live check's undo log; arena.h).
template <class T>
inline void arena_sti(u64 a, T v) {
    if (t_undo_on) [[unlikely]] undo_note(a, sizeof(T));
    sti<T>(a, v);
}
inline void arena_stf(u64 a, float v) {
    if (t_undo_on) [[unlikely]] undo_note(a, 4);
    stf(a, v);
}
#undef STI8
#undef STI16
#undef STI32
#undef STI64
#undef STS
#undef STD
#undef STQ
#define STI8(a, v) arena_sti<u8>(a, (u8)(v))
#define STI16(a, v) arena_sti<u16>(a, (u16)(v))
#define STI32(a, v) arena_sti<u32>(a, (u32)(v))
#define STI64(a, v) arena_sti<u64>(a, (u64)(v))
#define STS(n, a) arena_stf(a, r.v[n].f[0])
#define STD(n, a) (arena_stf(a, r.v[n].f[0]), arena_stf((a) + 4, r.v[n].f[1]))
#define STQ(n, a) (arena_stf(a, r.v[n].f[0]), arena_stf((a) + 4, r.v[n].f[1]), arena_stf((a) + 8, r.v[n].f[2]), arena_stf((a) + 12, r.v[n].f[3]))
''']
bad = []
bodies = []
table = []
for n in FUNCS:
    if n not in dyn:
        print(f'WARNING: {n} not exported', file=sys.stderr)
        continue
    a, s = dyn[n]
    if s < 8:
        continue  # the hook patch doesn't fit
    d = a2c.dem(n)
    osz = next((b for p, b in OBJ if d.startswith(p)), None)
    if osz is None:
        print(f'WARNING: no class size for {d}', file=sys.stderr)
        osz = 0
    body = a2c.translate(n, f'f_{a:x}')
    if '#error' in body:
        bad.append((n, re.findall(r'#error "a2c: ([^"]*)"', body)[:3]))
        continue
    bodies.append(f'// {d}')
    bodies.append(f'static void f_{a:x}(A64& r) {{')
    bodies.append('    u64 jt_ = 0, ex_a_ = 0, ex_v_ = 0;')
    bodies.append('    (void)jt_; (void)ex_a_; (void)ex_v_;')
    bodies.append(body.rstrip())
    bodies.append('}')
    table.append(f'    {{0x{a:x}, "{n}", f_{a:x}, 0x{osz:x}}},')
out += bodies
out.append('')
out.append('const ArenaA2cFn g_arena_a2c_fns[] = {')
out += table
out.append('};')
out.append('const int g_arena_a2c_nfns = sizeof g_arena_a2c_fns / sizeof g_arena_a2c_fns[0];')
out.append('}  // namespace soa::arena')
open(OUT, 'w').write('\n'.join(out) + '\n')
for n, e in bad:
    print(f'UNSUPPORTED {n}: {e}', file=sys.stderr)
print(f'{len(table)} bodies, {len(calls)} call targets, {len(bad)} unsupported', file=sys.stderr)
