#!/usr/bin/env -S sh -c 'exec "${0%/*}/py" "$0" "$@"'
"""Generates port/src/native/params/gen/infobase_a2c.cpp: the InfoBase container templates transcribed by a2c.py.

The response-parsing containers are one template each, instantiated per element class:
  - IInfoBaseMap<K, T>::DeserializeChild(AMap const*)   (map keyed by id: clear, then per entry
    ConvertParserValueToKey (virtual +0x20), find-or-emplace T, then T's Deserialize{Array,Child})
  - InfoBaseArray<T>::DeserializeArray(AArray const*)    (vector<T>: clear, then per map element
    construct / Initialize / InfoBase::DeserializeChild / push_back)
  - InfoBaseValueArray<V, CParameterPropertyValue<V, N>>::DeserializeArray (vector of properties)
  - InfoBaseNumberMap<T>::ConvertParserValueToKey  (uint, or a decimal string via istringstream)
  - InfoBaseMap<T>::ConvertParserValueToKey        (uint, or CHash32 of a string)
  - IInfoBaseMap<K, T>::DeserializeArray           (returns 0)
Each instantiation inlines its element's constructor / copy / destructor to a different degree, so
the bodies differ in shape and size (0x8 .. 0x7a0 bytes); rather than one hand-written template
with per-class hooks, every instantiation is transcribed instruction by instruction. The
Initialize() members are a lone RET (4 bytes: no room for the hook patch) and stay guest code.

The transcriptions are the reference now: the readable versions (port/src/native/params/infobase_rd.cpp,
one C++ version per template over the element class table infobase_table.inc) run in their place
unless SOA_INFOBASE_A2C=1, and the tests compare both with the original.

Calls: every call is a guest call (models_gcall, which calls native replacements directly);
virtual calls go through models_icall. Registration, switches and tests: infobase.cpp.

Usage: gen_infobase_a2c.py <out.cpp>
"""
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib  # noqa: E402 (before a2c / elfinfo: the default lib is 3.7.0's; tools/genlib.py)
_spec = importlib.util.spec_from_file_location('a2c', os.path.join(HERE, 'a2c.py'))
a2c = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(a2c)
L = a2c.L
OUT = sys.argv[1]

# kind -> mangled-name regex
KINDS = [
    ('map_child', r'^_ZN12IInfoBaseMapI.*E16DeserializeChildEPKN4Aska4ASON6AValue4AMapE$'),
    ('map_array', r'^_ZN12IInfoBaseMapI.*E16DeserializeArrayEPKN4Aska4ASON6AValue6AArrayE$'),
    ('array', r'^_ZN13InfoBaseArrayI.*E16DeserializeArrayEPKN4Aska4ASON6AValue6AArrayE$'),
    ('value_array', r'^_ZN18InfoBaseValueArrayI.*E16DeserializeArrayEPKN4Aska4ASON6AValue6AArrayE$'),
    ('key_number', r'^_ZN17InfoBaseNumberMapI.*E23ConvertParserValueToKeyEPKN4Aska4ASON6AValueE$'),
    ('key_hash', r'^_ZN11InfoBaseMapI.*E23ConvertParserValueToKeyEPKN4Aska4ASON6AValueE$'),
]

dyn = a2c.syms
FUNCS = []  # (kind, name, addr, size)
seen = set()
for kind, rx in KINDS:
    for n in sorted(dyn):
        if not re.match(rx, n):
            continue
        a, s = dyn[n]
        if a in seen or s < 8:
            continue
        seen.add(a)
        FUNCS.append((kind, n, a, s))

HOST = {
    'memset': 'memset((void*)X(0), (int)W(1), X(2));',
    'memcpy': 'memcpy((void*)X(0), (const void*)X(1), X(2));',
    'memmove': 'memmove((void*)X(0), (const void*)X(1), X(2));',
    'strlen': 'X(0) = (u64)strlen((const char*)X(0));',
}
guest_calls = {}


def fallback(kind, t, reg):
    if kind in ('blr', 'br'):
        return f'models_icall(r, {reg});'
    n = L.name(t)
    if n.startswith('PLT:'):
        pn = n[4:]
        if pn in HOST:
            return HOST[pn]
        guest_calls[t] = pn
        return f'models_gcall(r, LIB + 0x{t:x}); /* {pn} */'
    guest_calls[t] = n
    return f'models_gcall(r, LIB + 0x{t:x}); /* {a2c.dem(n)[:80]} */'


a2c.CALL_FALLBACK = fallback
a2c.EXCLUSIVE = True
a2c.NAN_EXACT = True
a2c.EXTRA_CALLS.clear()
for k in ('__cxa_guard_acquire', '__cxa_guard_release'):
    a2c.CALLS.pop(k, None)

out = ['''// GENERATED by tools/gen_infobase_a2c.py from libSOA.so's ARM64 code: do not edit by hand; regenerate.
// ''' + genlib.stamp() + '''
//
// The InfoBase container templates (IInfoBaseMap / InfoBaseArray / InfoBaseValueArray
// Deserialize*, InfoBaseNumberMap / InfoBaseMap ConvertParserValueToKey), every instantiation
// transcribed instruction by instruction by tools/a2c.py. Registration, switches and tests:
// infobase.cpp.
#pragma GCC optimize("fp-contract=off")
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wuninitialized"
#pragma GCC diagnostic ignored "-Wunused-variable"
#include <cstdlib>
#include <cstring>

#include "core/cpu.h"
#include "native/engine/math/aska_math.h"
#include "native/params/infobase.h"
#include "native/models/models.h"

namespace soa::infobase {
using namespace ::soa::aska;
using namespace ::soa::aska::a2c;
using namespace ::soa::models;
using a2c::u64;
using a2c::u32;
''']
bad = []
bodies = []
for kind, n, a, s in FUNCS:
    body = a2c.translate(n, f'f_{a:x}')
    if '#error' in body:
        bad.append((n, re.findall(r'#error "a2c: ([^"]*)"', body)[:3]))
        continue
    bodies.append(f'// {a2c.dem(n)}')
    bodies.append(f'static void f_{a:x}(A64& r) {{')
    bodies.append('    u64 jt_ = 0, ex_a_ = 0, ex_v_ = 0;')
    bodies.append('    (void)jt_; (void)ex_a_; (void)ex_v_;')
    bodies.append(body.rstrip())
    bodies.append('}')
    bodies.append(f'static void h_{a:x}(Cpu& c) {{ models_run_hook(c, f_{a:x}); }}')
out += bodies
out.append('')
out.append('const InfoBaseFn g_infobase_fns[] = {')
bad_names = {n for n, _ in bad}
for kind, n, a, s in FUNCS:
    if n in bad_names:
        continue
    out.append(f'    {{0x{a:x}, 0x{s:x}, "{n}", InfoBaseKind::{kind}, f_{a:x}, h_{a:x}}},')
out.append('};')
out.append('const int g_infobase_nfns = sizeof g_infobase_fns / sizeof g_infobase_fns[0];')
out.append('}  // namespace soa::infobase')
open(OUT, 'w').write('\n'.join(out) + '\n')
for n, e in bad:
    print(f'UNSUPPORTED {n}: {e}', file=sys.stderr)
kinds = {}
for kind, n, a, s in FUNCS:
    kinds[kind] = kinds.get(kind, 0) + 1
print(f'{len(FUNCS) - len(bad)} bodies ({kinds}), {len(guest_calls)} guest call targets, {len(bad)} unsupported',
      file=sys.stderr)
