#!/usr/bin/env -S sh -c 'exec "${0%/*}/py" "$0" "$@"'
"""Which server APIs the replay corpora (server/tests/replay/) cover, and which they don't.

    tools/replay_coverage.py [--server build/server/soa-server] [--write]

Replays every corpus once (soa-server --replay, as tools/server_replay_diff.sh does) and reads its
errors.txt (`<n> <Method> <code>`: 0 accepted, a number refused, `not-handled`). An API counts as
**covered** when some corpus other than `api-sweep` has it accepted (code 0); the sweep calls
every API once without arguments, which mostly proves the handler exists. Compared with
`soa-server --list-apis` (the methods the library answers, and the file that answers each).

Prints the report; --write also writes server/tests/replay/COVERAGE.md (committed; regenerate it
after adding a corpus). The rule for later agents: an API in the gap list gets a corpus (a few
`req` lines in an existing or new corpus, server/tests/replay/README.md) before anyone runs a game
session to test a change to it; a replay takes seconds, a session minutes.
"""
import argparse
import collections
import os
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import server_replay_diff as rd  # noqa: E402

SWEEP = "api-sweep"


def list_apis(server):
    """{method: file or None} of the methods the server library answers."""
    out = subprocess.run([server, "--list-apis"], capture_output=True, text=True, cwd=REPO).stdout
    apis = {}
    for ln in out.splitlines():
        f = ln.split("\t")
        if len(f) >= 3:
            apis[f[0]] = None if f[2] == "-" else f[2]
    return apis


def corpus_codes(server, work):
    """{corpus: {method: Counter(code)}} from replaying every corpus."""
    res = {}
    procs = []
    for c in rd.corpora([]):
        name = os.path.basename(c.rstrip("/"))
        procs.append((name, rd.start(server, c, os.path.join(work, name))))
    for name, p in procs:
        out, _ = p.communicate()
        if p.returncode:
            sys.exit("replay_coverage: %s: soa-server --replay exited %d:\n%s" % (name, p.returncode, out))
        codes = collections.defaultdict(collections.Counter)
        for ln in open(os.path.join(work, name, "errors.txt")):
            f = ln.split()
            if len(f) >= 3:
                codes[f[1]][f[2]] += 1
        res[name] = codes
    return res


def coverage(server):
    work = tempfile.mkdtemp(prefix="replay-coverage.")
    try:
        apis = list_apis(server)
        codes = corpus_codes(server, work)
    finally:
        shutil.rmtree(work, ignore_errors=True)
    return apis, codes


def report(apis, codes):
    covered, refused, sweep_only, none = {}, {}, {}, []
    for m in sorted(a for a, f in apis.items() if f):
        acc = sorted(c for c, cc in codes.items() if c != SWEEP and cc.get(m, {}).get("0"))
        if acc:
            covered[m] = acc
            continue
        other = sorted("%s (%s)" % (c, ",".join(sorted(cc[m]))) for c, cc in codes.items() if c != SWEEP and m in cc)
        if other:
            refused[m] = other
        elif m in codes.get(SWEEP, {}):
            sweep_only[m] = ",".join(sorted(codes[SWEEP][m]))
        else:
            none.append(m)
    lines = ["# Replay-corpus coverage of the server APIs", "",
             "Generated by `tools/replay_coverage.py --write` (do not edit). An API is covered when a corpus other than "
             "`api-sweep` has it accepted (code 0). **Rule:** before testing a change to an API in the gap lists with a game "
             "session, add a corpus for it (server/tests/replay/README.md): a replay takes seconds.", "",
             "Answered by the library: %d. Covered: %d. Only refused or not handled: %d. Only in the argument-less sweep: %d. "
             "In no corpus: %d." % (sum(1 for f in apis.values() if f), len(covered), len(refused), len(sweep_only), len(none)), "",
             "## Gaps: only refused (or not handled) outside the sweep", ""]
    lines += ["- `%s` (%s): %s" % (m, apis[m], "; ".join(v)) for m, v in refused.items()] or ["(none)"]
    lines += ["", "## Gaps: only the sweep's argument-less call (its code)", ""]
    lines += ["- `%s` (%s): %s" % (m, apis[m], v) for m, v in sweep_only.items()] or ["(none)"]
    lines += ["", "## Gaps: in no corpus", ""]
    lines += ["- `%s` (%s)" % (m, apis[m]) for m in none] or ["(none)"]
    lines += ["", "## Covered (accepted in)", ""]
    lines += ["- `%s` (%s): %s" % (m, apis[m], ", ".join(v)) for m, v in covered.items()]
    return "\n".join(lines) + "\n", covered, refused, sweep_only, none


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--server", default=os.path.join(REPO, "build/server/soa-server"))
    ap.add_argument("--write", action="store_true", help="write server/tests/replay/COVERAGE.md")
    ap.add_argument("--check", action="store_true", help="exit 1 when server/tests/replay/COVERAGE.md is out of date")
    a = ap.parse_args()
    apis, codes = coverage(os.path.abspath(a.server))
    text, covered, refused, sweep_only, none = report(apis, codes)
    path = os.path.join(REPO, "server/tests/replay/COVERAGE.md")
    if a.check:
        cur = open(path).read() if os.path.exists(path) else ""
        ok = cur == text
        print("replay_coverage --check: %s" % ("server/tests/replay/COVERAGE.md is current" if ok else
                                               "FAIL: COVERAGE.md is out of date (tools/replay_coverage.py --write)"))
        return 0 if ok else 1
    if a.write:
        with open(path, "w") as f:
            f.write(text)
    print(text if not a.write else "wrote server/tests/replay/COVERAGE.md")
    print("covered %d, gaps %d (refused-only %d, sweep-only %d, none %d)" %
          (len(covered), len(refused) + len(sweep_only) + len(none), len(refused), len(sweep_only), len(none)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
