#!/usr/bin/env -S sh -c 'exec "${0%/*}/py" "$0" "$@"'
"""docs/server-rules.md's structure and its generated register (docs/history/PLAN-readability.md R20).

    tools/server_rules_doc.py --check     the register is fresh and every section has a stable anchor
    tools/server_rules_doc.py --write     regenerate the register in place
    tools/server_rules_doc.py --anchors   list the anchors (id, heading)

The doc has one `##` section per `server/src/api/<domain>/` folder (plus the conventions, the
server-wide core and the register). Every `##` and `###` heading has an explicit anchor on the line
above it, `<a id="titles"></a>`, which is what code comments link (`docs/server-rules.md#titles`);
the anchors stay when a heading's wording changes. --check fails on a `##` / `###` heading without
one, a repeated anchor, or an in-doc link (`](#x)`) to no anchor.

**The register** ("Register of (c) and (d) rules the player can see") is generated from the
labels: every table under a heading that starts with "Player-visible (c) and (d) rules", in doc
order, one register row per table row, with the domain section it sits in and a link to the table.
The tables keep their own columns (Rule and Label, optionally Area and "Why it's needed / how to
check"); a row's text is copied verbatim. Edit the domain's table, then run --write; --check (T0's
`server-docs`, through tools/check_server_docs.sh) fails while the register is stale.
"""
import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(REPO, "docs", "server-rules.md")
BEGIN = "<!-- register: generated by tools/server_rules_doc.py --write from the domains' \"Player-visible (c) and (d) rules\" tables; do not edit -->"
END = "<!-- /register -->"
SOURCE = "Player-visible (c) and (d) rules"
ANCHOR_RE = re.compile(r'^<a id="([A-Za-z0-9_-]+)"></a>\s*$')
HEAD_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
COLS = ("Area", "Rule", "Label", "Why it's needed / how to check")


def cells(row):
    """The cells of a markdown table row (escaped pipes kept)."""
    row = row.strip()
    parts = re.split(r"(?<!\\)\|", row[1:-1] if row.endswith("|") else row[1:])
    return [c.strip() for c in parts]


def parse(lines):
    """[(level, title, anchor or None, line index)] of the headings outside code fences."""
    heads, in_code, prev = [], False, None
    for i, ln in enumerate(lines):
        if ln.startswith("```"):
            in_code = not in_code
        if in_code:
            continue
        m = HEAD_RE.match(ln)
        if m:
            a = ANCHOR_RE.match(prev or "")
            heads.append((len(m.group(1)), m.group(2), a.group(1) if a else None, i))
        if ln.strip():
            prev = ln
    return heads


def register_rows(lines):
    """The register's rows from the source tables, in doc order."""
    heads = parse(lines)
    rows = []
    in_reg = False
    for k, (lvl, title, anchor, i) in enumerate(heads):
        end = heads[k + 1][3] if k + 1 < len(heads) else len(lines)
        if not title.startswith(SOURCE):
            continue
        domain = next((h for h in reversed(heads[:k]) if h[0] == 2), None)
        dom_id = domain[2] if domain and domain[2] else "?"
        header = None
        for ln in lines[i + 1:end]:
            s = ln.strip()
            if BEGIN in s:
                in_reg = True
            if END in s:
                in_reg = False
            if in_reg or not s.startswith("|"):
                header = None if not s.startswith("|") else header
                continue
            c = cells(s)
            if header is None:
                header = c
                continue
            if all(re.fullmatch(r":?-+:?", x) for x in c):
                continue
            row = dict(zip(header, c))
            rows.append(("[%s](#%s)" % (dom_id, anchor or dom_id),) + tuple(row.get(col, "") for col in COLS))
    return rows


def render(rows):
    out = [BEGIN, "| Section | " + " | ".join(COLS) + " |", "|---|---|---|---|---|"]
    for r in rows:
        out.append("| " + " | ".join(r) + " |")
    out.append(END)
    return out


def regenerate(lines):
    try:
        b = next(i for i, ln in enumerate(lines) if ln.strip() == BEGIN)
        e = next(i for i, ln in enumerate(lines) if ln.strip() == END)
    except StopIteration:
        return None
    src = lines[:b] + lines[e + 1:]
    return lines[:b] + render(register_rows(src)) + lines[e + 1:]


def problems(lines):
    probs = []
    heads = parse(lines)
    ids = {}
    for lvl, title, anchor, i in heads:
        if lvl in (2, 3) and not anchor:
            probs.append("line %d: heading without an anchor above it: %s" % (i + 1, title))
        if anchor:
            if anchor in ids:
                probs.append("line %d: anchor #%s repeated (line %d)" % (i, anchor, ids[anchor]))
            ids[anchor] = i
    anchors = set(ids)
    for i, ln in enumerate(lines):
        for a in re.findall(r"\]\(#([A-Za-z0-9_-]+)\)", ln):
            if a not in anchors:
                probs.append("line %d: link to no anchor: #%s" % (i + 1, a))
    new = regenerate(lines)
    if new is None:
        probs.append("no register markers (%s ... %s)" % (BEGIN, END))
    elif new != lines:
        probs.append("the register is stale: run tools/server_rules_doc.py --write")
    return probs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--write", action="store_true")
    g.add_argument("--anchors", action="store_true")
    ap.add_argument("--doc", default=DOC)
    a = ap.parse_args()
    lines = open(a.doc, encoding="utf-8").read().split("\n")
    if a.anchors:
        for lvl, title, anchor, i in parse(lines):
            if anchor:
                print("%s\t%s %s" % (anchor, "#" * lvl, title))
        return 0
    if a.write:
        new = regenerate(lines)
        if new is None:
            print("no register markers", file=sys.stderr)
            return 1
        open(a.doc, "w", encoding="utf-8").write("\n".join(new))
        print("register: %d rows" % len(register_rows(lines)))
        return 0
    probs = problems(lines)
    for p in probs:
        print(p)
    n = sum(1 for _, _, a_, _ in parse(lines) if a_)
    print("docs/server-rules.md: %d anchors, register %d rows, %d problem(s)" % (n, len(register_rows(lines)), len(probs)))
    return 1 if probs else 0


if __name__ == "__main__":
    sys.exit(main())
