# The fonts built into the programs: Noto Sans JP (Noto Sans CJK's Japanese subset, with Latin; SIL
# Open Font License 1.1), the face Android's WebView draws the game's pages with. Used by the
# keyboard's text box (runtime/src/app/text_overlay.cpp, FreeType: regular) and the web view
# (webview/src/fonts.cpp, stb_truetype: regular and bold), from memory: common/include/soa/fonts.h.
#
# Downloaded at configure time from github.com/notofonts/noto-cjk at the Sans2.004 tag's commit into
# <build>/fonts/, each checked against its SHA-256 (a present file with the right hash is not fetched
# again), and assembled into the static library soa_fonts with the assembler's .incbin: one object
# file per font, so a program gets only the faces it uses (the linker takes an archive's members
# by need). The license text goes into the release packages' THIRD-PARTY-NOTICES.txt
# (tools/package.py, from <build>/fonts/LICENSE-NotoSansJP.txt).
set(SOA_FONTS_COMMIT 523d033d6cb47f4a80c58a35753646f5c3608a78)  # tag Sans2.004
set(_soa_fonts_url https://raw.githubusercontent.com/notofonts/noto-cjk/${SOA_FONTS_COMMIT})
# symbol (soa/fonts.h) | file name | path in the repository | SHA-256; no symbol: not built in
set(_soa_fonts
  "soa_font_regular|NotoSansJP-Regular.otf|Sans/SubsetOTF/JP/NotoSansJP-Regular.otf|dff723ba59d57d136764a04b9b2d03205544f7cd785a711442d6d2d085ac5073"
  "soa_font_bold|NotoSansJP-Bold.otf|Sans/SubsetOTF/JP/NotoSansJP-Bold.otf|1b0edfb500b73a4fa8a4fcaae1bbbd403994e08e73e3e0da37e70d3853f42c5f"
  "|LICENSE-NotoSansJP.txt|LICENSE|6a73f9541c2de74158c0e7cf6b0a58ef774f5a780bf191f2d7ec9cc53efe2bf2")

set(SOA_FONTS_DIR ${CMAKE_BINARY_DIR}/fonts)
set(_soa_fonts_sources)
foreach(_f IN LISTS _soa_fonts)
  string(REPLACE "|" ";" _f "${_f}")
  list(GET _f 0 _sym)
  list(GET _f 1 _name)
  list(GET _f 2 _src)
  list(GET _f 3 _sha)
  set(_dst ${SOA_FONTS_DIR}/${_name})
  file(DOWNLOAD ${_soa_fonts_url}/${_src} ${_dst} EXPECTED_HASH SHA256=${_sha} TLS_VERIFY ON STATUS _st)
  list(GET _st 0 _rc)
  if(NOT _rc EQUAL 0)
    file(REMOVE ${_dst})
    message(FATAL_ERROR "fonts: can't download ${_soa_fonts_url}/${_src}: ${_st} (cmake/fonts.cmake)")
  endif()
  if(_sym)
    # <sym>[] .. <sym>_end[]: the file's bytes, read-only (ELF .rodata, PE .rdata)
    set(_cpp ${SOA_FONTS_DIR}/${_sym}.cpp)
    file(CONFIGURE OUTPUT ${_cpp} @ONLY CONTENT [[
// Generated by cmake/fonts.cmake: @_name@ built in (soa/fonts.h).
#ifdef _WIN32
#define SOA_RODATA ".section .rdata,\"dr\"\n"
#else
#define SOA_RODATA ".section .rodata\n"
#endif
asm(SOA_RODATA
    ".balign 16\n"
    ".globl @_sym@\n"
    "@_sym@:\n"
    ".incbin \"@_dst@\"\n"
    ".globl @_sym@_end\n"
    "@_sym@_end:\n"
    ".byte 0\n"
    ".text\n");  // (back to code; COFF has no .previous)
]])
    set_source_files_properties(${_cpp} PROPERTIES OBJECT_DEPENDS ${_dst})
    list(APPEND _soa_fonts_sources ${_cpp})
  endif()
endforeach()

add_library(soa_fonts STATIC ${_soa_fonts_sources})
target_link_libraries(soa_fonts PUBLIC soa_env)  # (its header: soa/fonts.h)
